### PR TITLE
default to a released version of the operator

### PR DESCRIPTION
**Pull request by gregwebs**
This is the latest release of the operator and the version that I use.

### CODE REVIEW

**Comment by weekface** [comment]
There are many [fixes](https://github.com/pingcap/tidb-operator/releases) from `v1.0.0-beta.1-p2`, so it is better to use `latest` instead of `v1.0.0-beta.1-p2` before the next release.

**Comment by cofyc** [comment]
I guess this is going to fix https://github.com/pingcap/tidb-operator/issues/223. 

It's best practice to use a version tag in production deployment, we should recommend users to use the version tag instead of `latest`.  Using `latest`, users may encounter an unexpected upgrade when pods are migrated to another node even if they did nothing. Because users may apply our default values without modification, so this LGTM.

If `v1.0.0-beta.1-p2` is not a recommended version, we can hold this PR until the next release.

**Comment by gregwebs** [comment]
@weekface you need to create a new stable release then

**Comment by weekface** [comment]
Yes, we will release a new version recently.

**Pull request closed without merging**
