### PR TITLE
automatically set the scheduler K8s version

### PR DESCRIPTION
**Pull request by gregwebs**
This is tested to work on GKE. If this approach is approved, we will need to update some docs.

There is some relation to #278: after this change one should perform a helm upgrade when the K8s version changes (normally this would only matter for a major version change).

It is also possible to try to construct the string from Capabilities.KubeVersion.Major + Capabilities.KubeVersion.Minor.
However, that give me `1.12+` rather than `1.12.5`. So the GitVersion approach seems to match our user guide.

### CODE REVIEW

**Comment by tennix** [comment]
This looks great! Previously we use hyperkube image built by coreos hosted on quay.io. And the image is `quay.io/coreos/hyperkube:v1.10.2_coreos.0`, but the `GitVersion` returned by apiserver is `v1.10.2+coreos.0`. So this approach doesn't works. But now after CoreOS is acquired by RedHat, [quay.io](https://quay.io/repository/coreos/hyperkube?tab=tags) doesn't have newer versions (>= v1.11) of hyperkube image.

I'm not sure if this can still work for other registry images and I guess it's quite fragile. But if it works for `gcr.io/google-containers/hyperkube` I think we can add this to values.yaml to improve GKE users' experience and notify user in the documentation that this is only tested on GKE.

**Comment by gregwebs** [comment]
Users on other platforms besides GKE will still pull this pulbic image from the gcr.io without issue (unless they are behind the GFW). But yes, their GitVersion may not match. We should be able to make a more complicated function that can accomodate different environments. For example that can also remove the `+`.

**Pull request merged**
