### PR TITLE
chore(development env): unified the DinD development environment

### PR DESCRIPTION
**Pull request by onlymellb**
The purpose of this PR is to unify the development environment of developers at home and abroad by setting environment variables `KUBE_REPO_PREFIX`. This script will do the following at startup.

- Launch a k8s v1.10 cluster with flannel network plugin
- Install a docker registry in DinD env, the defaults port of the registry is `5000`, which can be changed by setting the environment variable `REGISTRY_PORT`.
- Deploy tiller in k8s 
- Deploy local volume provisioner in k8s
- Create PV mount points on all Kube nodes except the master node, you can control the number of created PVS by setting the environment variable PV_NUMS. All PV directories will be mounted in the host's `YOU-TIDB-OPERATOR-DIR/data` directory.
- Create TidbCluster CRD object and e2e namespace `tidb-operator-e2e`
- Start and stop an existing cluster with the commands `./dind-cluster-v1.10.sh stop` and `./dind-cluster-v1.10.sh start`
- Rebuild the k8s cluster with the commands `./dind-cluster-v1.10.sh clean` and `./dind-cluster-v1.10.sh up`

PTAL @tennix @weekface @xiaojingchen @gregwebs

### CODE REVIEW

**Comment by tennix** [comment]
I think it's better to mount a host directory as registry directory too.

**Comment by tennix** [comment]
Kubernetes dashboard can't be accessed by http://localhost:8080/ui

**Comment by gregwebs** [comment]
This looks great! Seems like we need some updates to the docs, including the DinD tutorial.
Right now I get an error at the end of running this.

``` sh
./manifests/local-dind/dind-cluster-v1.10.sh: line 1840: replace_repo_prefix: unbound variable
error: no objects passed to apply
➜  tidb-operator git:(onlymellb/unified-development-env) 
```

**Comment by gregwebs** [comment]
Flannel previously failed for me, but seems to be working now when using this :)

**Comment by gregwebs** [comment]
One problem I have always had with these setup scripts is that I cannot change NUM_NODES without cleaning. It would be great to address that in another PR.

**Comment by onlymellb** [comment]
@gregwebs I have fixed the problem without variable `replace_repo_prefix` definition, In this PR if you have already started the k8s cluster, you can't dynamically scale out the node by setting the NUM_NODES environment variable.

**Pull request merged**
