### PR TITLE
fix remoteWrite parse error

### PR DESCRIPTION
**Pull request by better0332**
### What problem does this PR solve?
fix remoteWrite parse error

### What is changed and how does it work?
use golang standard library `https://pkg.go.dev/net/url#Parse` to parse remoteWrite

add UT TestGenerateRemoteWrite only for url

### Code changes

- [*] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [*] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
@better0332 Please fix the CI.

**Comment by DanielZhangQD** [comment]
Could you please add the test result in the PR description?
For example, which TidbMonitor CR did you test and what's the test result?

**Comment by better0332** [comment]
> Could you please add the test result in the PR description?
> For example, which TidbMonitor CR did you test and what's the test result?

**Comment by mikechengwei** [comment]
LGTM

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
