### PR TITLE
optimize prometheus operator example

### PR DESCRIPTION
**Pull request by mikechengwei**
### What problem does this PR solve? 
 #2164 
### What is changed and how does it work?
optimize prometheus operator example serviceMonitor configuration.
### Check List 
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change

Side effects

 - None

### CODE REVIEW

**Comment by Yisaer** [comment]
I think #2654 have already solved this problem.

**Comment by mikechengwei** [comment]
Yes , i will fix prometheus operator example serviceMonitor configuration.

**Comment by mikechengwei** [comment]
wait for #2654  merge.

**Comment by mikechengwei** [comment]
@Yisaer Do you have time to merge this pr?

**Comment by cofyc** [comment]
done, thanks!

**Pull request merged**
