### PR TITLE
Should use GB/MB rather than GiB/MiB for backward compatibility with old TiKV versions

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 

fix bug in https://github.com/pingcap/tidb-operator/pull/942.

We should use GB/MB rather than GiB/MiB for backward compatibility with old TiKV versions.

### Check List 

Tests 

Unit test
E2E test

### Does this PR introduce a user-facing change?:
 
 ```release-note

 ```

### CODE REVIEW

**Comment by weekface** [comment]
Do we need to cherry-pick this PR together with https://github.com/pingcap/tidb-operator/pull/942 to `release-1.0`?

**Comment by cofyc** [comment]
> Do we need to cherry-pick this PR together with #942 to release-1.0?
I don't think it is necessary. It's not a critical bug.

**Pull request merged**
