### PR TITLE
update tidb default version to v3.0.8

### PR DESCRIPTION
**Pull request by shonge**
### What problem does this PR solve? 
update tidb default version to v3.0.8
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test

Code changes

 - Has Helm charts change
 - Has Go code change

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:
 
 ```release-note
Upgrade the default TiDB version to v3.0.8
 ```

### CODE REVIEW

**Comment by shonge** [comment]
@weekface PTAL

**Comment by shonge** [comment]
E2E test in jenkins ci pipeline got  this err:
```
[2019-12-27T05:39:22.988Z] [8] I1227 05:39:13.797949      17 actions.go:1386] tidbcluster: tidb-cluster-1165/cluster .status.PD.Members count(0) != 3
[2019-12-27T05:40:19.147Z] [8] I1227 05:40:13.799007      17 actions.go:1386] tidbcluster: tidb-cluster-1165/cluster .status.PD.Members count(0) != 3
[2019-12-27T05:41:15.300Z] [8] I1227 05:41:13.797925      17 actions.go:1386] tidbcluster: tidb-cluster-1165/cluster .status.PD.Members count(0) != 3
[2019-12-27T05:41:41.312Z] Sending interrupt signal to process
[2019-12-27T05:41:41.312Z] Killing processes
[2019-12-27T05:41:41.595Z] kill finished with exit code 0
[2019-12-27T05:41:41.801Z] Terminated
[2019-12-27T05:41:41.801Z] Terminated
[2019-12-27T05:41:41.801Z] Deleting cluster "tidb-operator" ...
[2019-12-27T05:41:41.841Z] script returned exit code 143
```
How to describe pd sts or trace pod logs?

**Comment by cofyc** [comment]
`tls` is enabled when tidb version >= 3.0.5, stuck when tls is enabled?
logs: https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/operator_ghpr_e2e_test_kind/runs/1785/nodes/68/steps/158/log/?start=0

**Comment by shonge** [comment]
Pass e2e basic testing.
./hack/e2e.sh -- --ginkgo.focus='Basic'
```
• [SLOW TEST:1305.624 seconds]
[tidb-operator] TiDBCluster
/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:64
  Basic: Deploying, Scaling, Update Configuration
  /go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:107
    [TiDB Version: v2.1.18] cluster5
    /go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:115
------------------------------
SDec 31 03:10:54.299: INFO: Running AfterSuite actions on all nodes
Dec 31 03:10:54.299: INFO: Running AfterSuite actions on node 1

Ran 2 of 13 Specs in 2921.518 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 11 Skipped
PASS

Ginkgo ran 1 suite in 48m41.59352291s
Test Suite Passed
Deleting cluster "tidb-operator" ...
```

**Comment by cofyc** [comment]
tls test is in `Upgrading TiDB Cluster` test, so ginkgo focus should be `Upgrading\sTiDB\sCluster'

**Comment by shonge** [comment]
> tls test is in `Upgrading TiDB Cluster` test, so ginkgo focus should be `Upgrading\sTiDB\sCluster'

OK, I will use ginkgo.focus='Upgrading TiDB Cluster' and try it again.

**Comment by cofyc** [comment]
wait for https://github.com/pingcap/tidb-operator/issues/1450 to be fixed

**Comment by cofyc** [comment]
no need to rerun code-gen

**Comment by cofyc** [comment]
`YEAR` is removed in #1458, all you need to do is merging the master or rebasing on the it

**Comment by cofyc** [comment]
please update this line too, we use this constant in some e2e tests now.
https://github.com/pingcap/tidb-operator/blob/cbee814dccc1b7093779a33071d2760cbace082a/tests/e2e/util/image/image.go#L31

**Comment by cofyc** [comment]
Thanks for your patience!

**Comment by cofyc** [comment]
@weekface @aylei take a look?

**Comment by cofyc** [comment]
` [tidb-operator][Serial] [Feature: Defaulting and Validating] should perform defaulting and validating properly ` fails again which is being fixed in #1533
I'm going to merge this manually.

**Comment by cofyc** [comment]
hi, @shonge can you cherry-pick this PR manually?

**Pull request merged**
