### PR TITLE
increase HTTP client timeout to 5 seconds when to sync pd status

### LINKED ISSUE #154: Blocked when creating a tidb cluster because the state of getting pd failed
the log of tidb-controller-manager  
```
E1030 03:02:59.483099       1 pd_member_manager.go:206] failed to sync TidbCluster: [test1-exp4-cat0-tidb-cluster/tidb-cluster]'s status, error: Get http://tidb-cluster-pd.test1-exp4-cat0-tidb-cluster:2379/pd/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I1030 03:02:59.484234       1 tidb_cluster_control.go:100] tidbcluster: [test1-exp4-cat0-tidb-cluster/tidb-cluster]'s pd cluster is not running.
E1030 03:03:29.483254       1 pd_member_manager.go:206] failed to sync TidbCluster: [test1-exp4-cat0-tidb-cluster/tidb-cluster]'s status, error: Get http://tidb-cluster-pd.test1-exp4-cat0-tidb-cluster:2379/pd/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I1030 03:03:29.484312       1 tidb_cluster_control.go:100] tidbcluster: [test1-exp4-cat0-tidb-cluster/tidb-cluster]'s pd cluster is not running.
```  
but I check the health state of pd  is `true`, I exec this command in the   tidb-controller-manager  pod
```
/ # wget -qO- http://tidb-cluster-pd.test1-exp4-cat0-tidb-cluster:2379/pd/health
[
  {
    "name": "tidb-cluster-pd-0",
    "member_id": 2384070400007428437,
    "client_urls": [
      "http://tidb-cluster-pd-0.tidb-cluster-pd-peer.test1-exp4-cat0-tidb-cluster.svc:2379"
    ],
    "health": true
  }
] 
```

### PR DESCRIPTION
**Pull request by cwen0**
fix #154 
@tennix @weekface @xiaojingchen PTAL, thanks

### CODE REVIEW

**Comment by gregwebs** [comment]
Should this be a config setting? Is there a way to monitor PD latency?

**Comment by tennix** [comment]
@gregwebs Did you mean making this value a command line argument of the controller-manager? I don't know if there's a metrics representing PD HTTP request latency. @nolouch PTAL

**Comment by tennix** [comment]
Yes, setting this in values.yaml means adding an option for controller-manager. We can add this and set 5 seconds as the default value which I think will cover most scenarios.

With #176, we can add PD latency metrics to tidb-operator's metrics. But I think PD itself should have such metrics, so I mentioned @nolouch to take a look.

**Pull request merged**
