### PR TITLE
change default tolerations type to an array

### PR DESCRIPTION
**Pull request by gregwebs**
I believe the default value is of the incorrect type object.

### CODE REVIEW

**Comment by gregwebs** [comment]
@tennix I though I did change them? I don't see the build failure log right now.

**Comment by tennix** [comment]
Yeah, because this change have no impact on e2e test. But we should keep the values file in sync with `images/tidb-operator-e2e/tidb-cluster-values.yaml`.

**Comment by gregwebs** [comment]
@tennix The file you mention was updated in the PR.

**Comment by tennix** [comment]
Oh, sorry my bad. We can merge it after the CI is finished.

**Pull request merged**
