### PR TITLE
Remove tcp and http ports for tiflash >= 7.1.0

### PR DESCRIPTION
**Pull request by zanmato1984**
### What problem does this PR solve?

The tcp_port and http_port are deprecated in tiflash since v7.1.0.

### What is changed and how does it work?

Remove those two ports for the corresponding versions.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by csuzhangxc — COMMENTED** [review]
`ci / pull (test)` needs to be fixed

**Pull request merged**
