### PR TITLE
charts: deprecate tidb-cluster and tidb-backup

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by KanShiori — APPROVED** [review]

**Review by csuzhangxc — APPROVED** [review]

**Comment by magicJie** [comment]
为什么要弃用tidb-cluster 和 tidb-backup，以后不推荐使用helm安装了么

**Comment by xhebox** [comment]
> 为什么要弃用tidb-cluster 和 tidb-backup，以后不推荐使用helm安装了么

是的, 很早就在文档里提过了, 1.1还是1.2. 但是charts一直没改过, 导致经常受误会. 新版本使用kubectl来创建这两个CR, 但是`tidb-operator`本身还是可以用helm来安装的.

Yes, these two charts are deprecated for a long time(from 1.1 or 1.2)? But charts are not updated, and a lot misunderstood.

But you could still use charts to install `tidb-operator`. But we recommended to use `kubectl` to create `tidb-cluster/tidb-backup`.

**Pull request merged**
