### PR TITLE
ebs br: mark backup/restore failed when job failed

### LINKED ISSUE #5293: ebs br: When the restore data pod fails, the volumerestore task status is not set to failed
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumerestore
2. do chaos, Kill restore data container process

**What did you expect to see?**
1. volumerestore status is failed

**What did you see instead?**
1. volumerestore is running 
d963e3f5-0616-4104-8573-ece477b5d3b1
f1401891-c047-48c2-8e11-ce29658939bf

### LINKED ISSUE #5331: ebs br: VolumeBackup failed due to resuming GC and scheduling
## Bug Report

**What did you do?**

create a `VolumeBackup`

**What did you expect to see?**

backup successful

**What did you see instead?**

backup failed

img_v2_40cd688d-91ac-4bef-838a-0de521f56edg

also found log below

```
{"log":"I1013 01:37:16.376335       1 backup_controller.go:427] backup ebs-chaos-restore-2-tps-3060164-1-822/fed-ebs-tidb-operator-ebs-1 has failed pod backup-fed-ebs-tidb-operator-ebs-1-init-w5glk. original reason \n","stream":"stderr","time":"2023-10-13T01:37:16.376772246Z","kubernetes":{"pod_name":"tidb-controller-manager-tidb-operator-ebs-1-67fd59f6f7-m5z4g","namespace_name":"tidb-operator-ebs-1","pod_id":"ea7b5bfb-3b88-40e0-881c-959bd5add527","host":"[ip-10-234-158-20.us](http://ip-10-234-158-20.us/)-west-2.compute.internal","container_name":"tidb-operator","docker_id":"fc65a34f92fc4cb056ee73976e25f50aa3ea90854a06c7d1e164ceb3520e7d4e","container_hash":"wangle1321/tidb-operator@sha256:5a4b68dac573c6d481edef613597cd49b61178378f3cd6141be2258bba170891","container_image":"wangle1321/tidb-operator:202309261220"}}
```

### LINKED ISSUE #5405: When checking whether warmup has ended, if there are warmup jobs in other namespaces, it will interfere with the current results.
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumerestore in 2 namespace

**What did you expect to see?**
1. The two tasks are independent and will not interfere with each other

**What did you see instead?**
1.When checking whether warmup has ended, if there are warmup jobs in other namespaces, it will interfere with the current results.
img_v3_025c_93467d06-c855-444d-a914-d9befb3bf97g

### PR DESCRIPTION
**Pull request by WangLe1321**
### What problem does this PR solve?

1. Fix the bug that when resume GC and scheduling normally, but backup failed due to pod failure.
Closes #5331

2. Fix the bug that restore pod fails due to the container being killed, but restore status doesn't set failed.
Closes #5293 

3. Raise error when deleting EBS snapshot failed except snapshot not found, so that we can block backup deletion when EBS snapshots aren't all be deleted.

4. Close #5405 

### What is changed and how does it work?

For 1 and 2, watch job status in backup/restore controller. When job is failed but backup/restore status isn't failed, set status failed.

For 3, if encounter error except not found error, return the error.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by WangLe1321** [comment]
run-pull-e2e-kind-br

**Review by BornChanger — APPROVED** [review]

**Pull request merged**
