### PR TITLE
fix: type mismatch in TidbMonitor remoteTimeout

### PR DESCRIPTION
**Pull request by IMMORTALxJO**
### What problem does this PR solve?

Fix the bug where `tidbmonitor.spec.prometheus.remoteWrite.remoteTimeout` CRD only accepts integers:
```
Invalid value: "string": spec.prometheus.remoteWrite[0].remoteTimeout in body must be of type integer: "string"
```
However, if we pass an integer and check the operator logs, we will see that the operator fails to unmarshal the TiDBMonitor resource because it expected a string instead:
```
json: cannot unmarshal number into Go struct field RemoteWriteSpec.items.spec.prometheus.remoteWrite.remoteTimeout of type string
```
the definition of the struct field in code - [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go#L449C2-L449C15)

### What is changed and how does it work?

Changed field type in tidbmonitors CRD, from integer to string.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Fix type mismatch of `TidbMonitor` field `.spec.prometheus.remoteWrite.remoteTimeout`
```

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@IMMORTALxJO If we want to modify the CRD, we need to modify the Go struct in _types.go_ and then re-generate the CRD (`make generate`)

**Comment by IMMORTALxJO** [comment]
@csuzhangxc thank you, I've added the missing file with Go struct.

**Comment by csuzhangxc** [comment]
> @csuzhangxc thank you, I've added the missing file with Go struct.

It seems still need to re-generate other files, can you run `make generate`?

**Comment by IMMORTALxJO** [comment]
@csuzhangxc sorry for the delay, added `make generate` results to the commit.

**Comment by csuzhangxc** [comment]
@IMMORTALxJO can you fix the problem reported in CI? https://github.com/pingcap/tidb-operator/actions/runs/12186746269/job/34009983048?pr=5734

**Comment by IMMORTALxJO** [comment]
@csuzhangxc thank you, fixed the tests, please check

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
