### PR TITLE
fix ad-hoc full backup failure due to incorrect claimName

### PR DESCRIPTION
**Pull request by DanielZhangQD**
### What problem does this PR solve? 
ad-hoc backup will fail if use default backup name which is not rendered during helm install in backup-job.yaml.
### What is changed and how does it work?
Make helm render the backup name.
### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
   - ad-hoc backup with the default name
   - ad-hoc backup with the specified name

Code changes

 - Has Helm charts change

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:
 
 ```release-note
The ad-hoc backup will fail if use default backup name which is not rendered during helm install in backup-job.yaml.
 ```

### CODE REVIEW

**Comment by onlymellb** [comment]
The `restore.yaml` file also needs to be changed

**Comment by weekface** [comment]
This is a bug, add a release note.

**Comment by DanielZhangQD** [comment]
> The `restore.yaml` file also needs to be changed

Users need to specify the name during the restore, the auto-generated name will not be used.

**Pull request merged**
