### PR TITLE
fix some broken urls

### PR DESCRIPTION
**Pull request by weekface**
### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by Yisaer** [comment]
`docs-cn` uses [verify-link.sh`](https://github.com/pingcap/docs-cn/blob/master/scripts/verify-links.sh) to check whether there are any links unaccessible. Maybe we could add it into our CI checking process?

**Comment by weekface** [comment]
I think it is not necessary to check automatically now, veryfy-link.sh use `markdown-link-check`, values.yaml is YAML format however.

**Pull request merged**
