### PR TITLE
Fix publish 'nightly' charts

### LINKED ISSUE #4069: Helm Chart Errors
Using the latest TiDB Operator 1.1.13

It seems our Helm Chart needs to be looked at. I can deploy the tidb-cluster but get these Helm Erroros:
 helm repo update
Hang tight while we grab the latest from your chart repositories...
index.go:339: skipping loading invalid entry for chart "tidb-backup" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-backup" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-backup" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-cluster" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-cluster" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-cluster" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-drainer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-drainer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-drainer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-lightning" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-lightning" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-lightning" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-operator" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-operator" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-operator" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tikv-importer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tikv-importer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tikv-importer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
...Successfully got an update from the "pingcap" chart repository

### PR DESCRIPTION
**Pull request by KanShiori**
### What problem does this PR solve?

Fix #4069

### Code changes

- [ ] Has Go code change
- [x] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by KanShiori** [comment]
Maybe  we need to update the `index.yaml` in charts repository manually.

**Review by csuzhangxc — APPROVED** [review]

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
> Maybe we need to update the `index.yaml` in charts repository manually.

Yes, after this PR merged.

**Pull request merged**
