### PR TITLE
Update example file "tidb-cluster.yaml"

### LINKED ISSUE #4024: Update example file 'tidb-cluster.yaml'
## Feature Request

**Is your feature request related to a problem? Please describe:**

Type of `terminationGracePeriodSeconds` in example file 'tidb-cluster.yaml' is String, it should be **Int**.
https://github.com/pingcap/tidb-operator/blob/4ac9865b32f7c5292479b06892247918a84fe081/examples/advanced/tidb-cluster.yaml#L255

### PR DESCRIPTION
**Pull request by KanShiori**
### What problem does this PR solve?

Update  `terminationGracePeriodSeconds` in example file 'tidb-cluster.yaml' to be Int.

Closes #4024 

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Comment by KanShiori** [comment]
PTAL @DanielZhangQD

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Pull request merged**
