### PR TITLE
Update the TiCDC capture status info in the `status.ticdc`

### LINKED ISSUE #4001: Update the TiCDC capture status info in the `status.ticdc` of the TidbCluster CR
## Feature Request

**Is your feature request related to a problem? Please describe:**

1. We need to wait for the TiCDC to support the HTTP API https://github.com/pingcap/ticdc/issues/1869
2. We need to update the task info in the `status.ticdc` of the TidbCluster CR
```
Task list (`cdc cli changefeed list --pd=http://10.0.10.25:2379`)
[{
    "id": "simple-replication-task",
    "summary": {
      "state": "normal",
      "tso": 417886179132964865,
      "checkpoint": "2020-07-07 16:07:44.881",
      "error": null
    }
}]
```
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by KanShiori**
### What problem does this PR solve?

Closes #4001 

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [x] Manual test 
* Upgrade tidb-operator and check whether the *status* of 'TiCDC' contains field `version` and `isOwner`. 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
@KanShiori Please also update the test result in the `Manual test` section in the PR description.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
