### PR TITLE
status missed even if backup job succeeds

### LINKED ISSUE #3635: Backup CR status is not updated successfully even if no error returned from the update API
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**
Backup CR status:
k get bk
```
NAME BACKUPPATH BACKUPSIZE COMMITTS AGE
data-tidb-backup-s3-2020-12-09t01-07-00 s3://data/data-tidb-pd.data-2379-2020-12-09t01-07-00/ 638 kB 421390233041371137 9d
data-tidb-backup-s3-2020-12-10t01-07-00 s3://data/data-tidb-pd.data-2379-2020-12-10t01-07-00/ 641 kB 421412882584436737 8d
data-tidb-backup-s3-2020-12-11t01-07-00 s3://data/data-tidb-pd.data-2379-2020-12-11t01-07-00/ 663 kB 421435532159221761 7d8h
data-tidb-backup-s3-2020-12-12t01-07-00 s3://data/data-tidb-pd.data-2379-2020-12-12t01-07-00/ 667 kB 421458174271291393 6d8h
data-tidb-backup-s3-2020-12-13t01-07-00 s3://data/data-tidb-pd.data-2379-2020-12-13t01-07-00/ 671 kB 421480823499784193 5d8h
data-tidb-backup-s3-2020-12-17t01-07-00 s3://data/data-tidb-pd.data-2379-2020-12-17t01-07-00/ 688 kB 421585823983206401 17h
data-tidb-backup-s3-2020-12-18t01-07-00
```

Pod status:
```
backup-data-tidb-backup-s3-2020-12-18t01-07-00-nvxxt 0/1 Completed 0 9h
```

Log of tidb-controller-manager:
```
tidb-operator I1218 10:29:46.682856 1 backup_schedule_controller.go:96] BackupSchedule: data/data-tidb-backup-s3, still need sync: backup schedule data/data-tidb-backup-s3, the last backup data-tidb-backup-s3-2020-12-18t01-07-00 is still running, requeuing
```

Log of backup-data-tidb-backup-s3-2020-12-18t01-07-00-nvxxt:
kl backup-data-tidb-backup-s3-2020-12-18t01-07-00-nvxxt (prod-orscale-01-dm-ix7/data)
```
Create rclone.conf file.
/tidb-backup-manager backup --namespace=data --backupName=data-tidb-backup-s3-2020-12-18t01-07-00 --tikvVersion=v4.0.8 --cluster-tls=true --client-tls=true
I1218 01:09:49.873849 1 backup.go:71] start to process backup data/data-tidb-backup-s3-2020-12-18t01-07-00
I1218 01:09:49.909181 1 backup_status_updater.go:64] Backup: [data/data-tidb-backup-s3-2020-12-18t01-07-00] updated successfully
I1218 01:09:49.944903 1 backup_status_updater.go:64] Backup: [data/data-tidb-backup-s3-2020-12-18t01-07-00] updated successfully
I1218 01:09:49.947479 1 manager.go:176] cluster data/data-tidb-backup-s3-2020-12-18t01-07-00 tikv_gc_life_time is 10m0s
I1218 01:09:49.957034 1 manager.go:240] set cluster data/data-tidb-backup-s3-2020-12-18t01-07-00 tikv_gc_life_time to 72h success
I1218 01:09:49.957077 1 backup.go:67] Running br command with args: backup full --pd=data-tidb-pd.data:2379 --ca=/var/lib/cluster-client-tls/ca.crt --cert=/var/lib/cluster-client-tls/tls.crt --key=/var/lib/cluster-client-tls/tls.key --log-level=warn --storage=s3://data/data-tidb-pd.data-2379-2020-12-18t01-07-00/ --s3.provider=minio --s3.endpoint=[https://minio-xxxx-xx.xx.xx 
I1218 01:09:50.204338 1 backup.go:91] [2020/12/18 01:09:50.204 +00:00] [WARN] [version.go:146] ["BR version is too old, please consider use version 4.0.8 of BR"]
I1218 01:09:51.950963 1 backup.go:91]
I1218 01:09:51.951035 1 backup.go:106] Backup data for cluster data/data-tidb-backup-s3-2020-12-18t01-07-00 successfully
I1218 01:09:51.959285 1 manager.go:261] reset cluster data/data-tidb-backup-s3-2020-12-18t01-07-00 tikv_gc_life_time to 10m0s success
I1218 01:09:51.959299 1 manager.go:276] backup cluster data/data-tidb-backup-s3-2020-12-18t01-07-00 data to s3://data/data-tidb-pd.data-2379-2020-12-18t01-07-00/ success
I1218 01:09:52.010244 1 manager.go:291] Get br metadata for backup files in s3://data/data-tidb-pd.data-2379-2020-12-18t01-07-00/ of cluster data/data-tidb-backup-s3-2020-12-18t01-07-00 success
I1218 01:09:52.010282 1 manager.go:294] Get size 688249 for backup files in s3://data/data-tidb-pd.data-2379-2020-12-18t01-07-00/ of cluster data/data-tidb-backup-s3-2020-12-18t01-07-00 success
I1218 01:09:52.010302 1 manager.go:295] Get cluster data/data-tidb-backup-s3-2020-12-18t01-07-00 commitTs 421594081624064001 success
I1218 01:09:52.045241 1 backup_status_updater.go:64] Backup: [data/data-tidb-backup-s3-2020-12-18t01-07-00] updated successfully
```

### PR DESCRIPTION
**Pull request by DanielZhangQD**
### What problem does this PR solve?

Fix the issue that in some cases some fields, e.g. BACKUPPATH, BACKUPSIZE, COMMITTS, etc. in the status of Backup CR or Restore CR are missed even if the backup or restore job succeed.
Fix #3635
### What is changed and how does it work?

Root cause:
Take the Backup CR for example, and the Restore CR has a similar logic.
Currently, two controllers will update the status of Backup CR, one is the backup controller in the tidb-controller-manager Pod, which only updates the conditions slice in the status. The other is the controller in the backup-manager Pod which is the real backup job and will update all the fields in the status.
With the current status update logic, if something wrong with the update API call, the status updater will retrieve the latest Backup resource from the lister and replace the `status` field totally with the old status, so if the backup-manager Pod updates all the fields in the status and then the tidb-controller-manager Pod updates the conditions slice in the status, all the other fields updated by the backup-manager will be lost.
So we should update the status based on the latest status instead of the old status.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
  - Run `BackupSchedule` with BR
      -  The clean of the `Backup` CRs works as expected
      -  The status of the `Backup` is updated correctly even if an error occurs during the update:

```
E1230 07:06:10.482472       1 backup_status_updater.go:87] Failed to update backup [ns0/minio-br-2020-12-30t07-06-00], error: Operation cannot be fulfilled on backups.pingcap.com "minio-br-2020-12-30t07-06-00": the object has been modified; please apply your changes to the latest version and try again
I1230 07:06:10.498200       1 backup_status_updater.go:84] Backup: [ns0/minio-br-2020-12-30t07-06-00] updated successfully
```

```
# k get bk -n ns0
NAME                                  STATUS     BACKUPPATH                                                     BACKUPSIZE   COMMITTS             AGE
minio-br-2020-12-30t06-26-00          Complete   s3://backup/ns0/br/ns0-pd.ns0-2379-2020-12-30t06-26-00         278 kB       421870849284636673   38m
minio-br-2020-12-30t06-28-00          Complete   s3://backup/ns0/br/ns0-pd.ns0-2379-2020-12-30t06-28-00         278 kB       421870881108918275   36m
minio-br-2020-12-30t06-30-00          Complete   s3://backup/ns0/br/ns0-pd.ns0-2379-2020-12-30t06-30-00         278 kB       421870912146767873   34m
minio-br-2020-12-30t06-32-00          Complete   s3://backup/ns0/br/ns0-pd.ns0-2379-2020-12-30t06-32-00         278 kB       421870943866191875   32m
```

  - Run `BackupSchedule` with Dumpling
      -  The clean of the `Backup` CRs works as expected
      -  The status of the `Backup` is updated correctly even if an error occurs during the update:

```
E1230 07:08:09.489023       1 backup_status_updater.go:87] Failed to update backup [ns0/minio-dump-2020-12-30t07-08-00], error: Operation cannot be fulfilled on backups.pingcap.com "minio-dump-2020-12-30t07-08-00": the object has been modified; please apply your changes to the latest version and try again
I1230 07:08:09.890044       1 backup_status_updater.go:84] Backup: [ns0/minio-dump-2020-12-30t07-08-00] updated successfully
```

```
# k get bk -n ns0
NAME                                  STATUS     BACKUPPATH                                                     BACKUPSIZE   COMMITTS             AGE
minio-dump-2020-12-30t06-26-00        Complete   s3://backup/ns0/dumpling/backup-2020-12-30T06:26:16Z.tgz       721 B        421870849520566278   38m
minio-dump-2020-12-30t06-28-00        Complete   s3://backup/ns0/dumpling/backup-2020-12-30T06:28:15Z.tgz       721 B        421870880728809476   36m
minio-dump-2020-12-30t06-30-00        Complete   s3://backup/ns0/dumpling/backup-2020-12-30T06:30:15Z.tgz       721 B        421870912382697476   34m
```
    
  - Run `Restore` with BR and the status of the `Restore` is updated correctly even if an error occurs during the update:

```
E1230 06:45:05.777648       1 restore_status_updater.go:79] Failed to update resotre [ns1/br-minio0], error: Operation cannot be fulfilled on restores.pingcap.com "br-minio0": the object has been modified; please apply your changes to the latest version and try again
I1230 06:45:05.794604       1 restore_status_updater.go:76] Restore: [ns1/br-minio0] updated successfully
```

```
# k get rt -n ns1
NAME                 STATUS     STARTED                COMPLETED              COMMITTS             AGE
br-minio0            Complete   2020-12-30T06:44:53Z   2020-12-30T06:45:05Z   421870503280771073   28m
```

  - Run `Restore` with Lightning and the status of the `Restore` is updated correctly even if an error occurs during the update:

```
E1230 06:41:13.551646       1 restore_status_updater.go:79] Failed to update resotre [ns1/light-minio0], error: Operation cannot be fulfilled on restores.pingcap.com "light-minio0": the object has been modified; please apply your changes to the latest version and try again
I1230 06:41:13.568063       1 restore_status_updater.go:76] Restore: [ns1/light-minio0] updated successfully
```

```
# k get rt -n ns1
NAME                 STATUS     STARTED                COMPLETED              COMMITTS             AGE
light-minio0         Complete   2020-12-30T06:41:12Z   2020-12-30T06:41:13Z   421870441493430276   34m
```
### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Fix the issue that `commitTS` or other fields in status may be lost even if the backup job succeeds
```

### CODE REVIEW

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
@csuzhangxc @handlerww @dragonly PTAL.

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Review by handlerww — APPROVED** [review]
LGTM

**Pull request merged**
