### PR TITLE
Add the LocalTSOConfig for PD config

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve? 

Add the `LocalTSOConfig` for PD config.

### What is changed and how does it work?

Update the `pkg/apis/pingcap/v1alpha1/pd_config.go`

### Check List 

Tests 

 - Unit test
 - E2E test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has Go code change

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
@JmPotato From TiDB Operator v1.1.6, we have supported TOML configurations, you can refer to the [doc](https://docs.pingcap.com/tidb-in-kubernetes/dev/configure-a-tidb-cluster#configure-pd-parameters) for detail, so we do not need to maintain the struct definition of the configurations anymore, you can write any TOML config that is valid for PD.

**Comment by JmPotato** [comment]
> @JmPotato From TiDB Operator v1.1.6, we have supported TOML configurations, you can refer to the [doc](https://docs.pingcap.com/tidb-in-kubernetes/dev/configure-a-tidb-cluster#configure-pd-parameters) for detail, so we do not need to maintain the struct definition of the configurations anymore, you can write any TOML config that is valid for PD.

Thanks for pointing out! So should I close this PR directly?

**Comment by DanielZhangQD** [comment]
> > @JmPotato From TiDB Operator v1.1.6, we have supported TOML configurations, you can refer to the [doc](https://docs.pingcap.com/tidb-in-kubernetes/dev/configure-a-tidb-cluster#configure-pd-parameters) for detail, so we do not need to maintain the struct definition of the configurations anymore, you can write any TOML config that is valid for PD.
> 
> Thanks for pointing out! So should I close this PR directly?

Yes, you can close it.
Thanks for your contribution!

**Pull request closed without merging**
