### PR TITLE
Remove k8s cluster name from restore/warmup pod names

### PR DESCRIPTION
**Pull request by nkg-**
### What problem does this PR solve?
There is a [63 character limit](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names) for k8s pod names. Warmup pod names follow the [schema](https://github.com/pingcap/tidb-operator/blob/master/pkg/backup/restore/restore_manager.go#L981) {restore_pod_name}-{tidb_cluster_name}-tikv-{tikv_number}-warm-up". Where restore_pod_name follows the schema fed-{restore_name}-{k8s_cluster_name}. This can be pretty long, and likely to hit the character limit. And forces the various names to short in general. While restore pod names and tidb cluster names are easily updated, k8s cluster names are hard to change. And can be long. Real world example - m-tidb-test-a-ea1-us. This PR attempts to shorted the pod names. 

Closes https://tidb.support.pingcap.com/servicedesk/customer/portal/4/NAID-10085

### What is changed and how does it work?
This PR removes the k8s cluster name from the restore and warmup pod names. Its fine, since these pods operator in different physical k8s clusters. And don't need to be unique across k8s clusters. For example - For heterogeneous tidb clusters, tidb, tikv, pd names are already duplicate across k8s clusters. 

Since restore names are not unique anymore, some minor changes
1. Remove usage of restore name to in a map. And use k8s clsuter name instead.
2. Add k8s cluster name in logs.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by nkg-** [comment]
cc: @WangLe1321, @csuzhangxc

**Review by WangLe1321 — APPROVED** [review]
LGTM

**Review by BornChanger — APPROVED** [review]

**Comment by nkg-** [comment]
Test failures seem unrelated. Please advice.
1. [tidb-operator-pull-e2e-kind-across-kubernetes](https://ci.pingcap.net/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-across-kubernetes/detail/tidb-operator-pull-e2e-kind-across-kubernetes/3014/pipeline)
[2023-10-08T10:11:49.962Z] [2] [Fail] [Across Kubernetes] [Across Kubernetes: Basic] [It] Join cluster with existing data 
[2023-10-08T10:11:49.962Z] [2] [Fail] [Across Kubernetes] Start Script Version [It] migrate start script from v1 to v2  

2. [pull-e2e-kind](https://ci.pingcap.net/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/5146/pipeline/65). ERROR: failed to create cluster: failed to apply overlay network: command "docker exec --privileged -i tidb-operator-control-plane kubectl create --kubeconfig=/etc/kubernetes/admin.conf -f -" failed with error: exit status 1
 
/retest

**Comment by nkg-** [comment]
> license/cla Pending — Contributor License Agreement is not signed yet. 

Not sure why it shows as pending. I have signed it multiple times at this point.

**Comment by BornChanger** [comment]
> > license/cla Pending — Contributor License Agreement is not signed yet.
> 
> Not sure why it shows as pending. I have signed it multiple times at this point.

Please check if you are signing with the same id you used for the PR commit.

**Pull request merged**
