### PR TITLE
br: refactor volume snapshot backup to support across k8s clusters

### LINKED ISSUE #4998: Refactor volume snapshot backup process to support across k8s clusters
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by WangLe1321**
### What problem does this PR solve?

Refactor volume snapshot backup process to support backup across k8s clusters.

Closes #4998

### What is changed and how does it work?

Divide volume snapshot backup into 3 phases: `initialize`, `execute` and `teardown`

For `initialize` phase, create a backup pod to stop GC and PD schedules. This backup pod keeps running during backup. After stop GC and PD schedules successfully, the backup CR enters `VolumeBackupInitialized` status.

For `execute` phase, create another backup pod to take volumes snapshots of TiKV. It's the core phase. After volumes snapshots complete, the backup CR enters `VolumeBackupComplete` status.

For `teardown` phase, delete the job created in 'initialize' phase to resume GC and PD schedules and set backup CR to `Complete` status.

The state machine of volume snapshot backup in different phases is as followed:

state-machine

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by BornChanger — COMMENTED** [review]
Please add those minor change as we talk offline, other lgtm

**Comment by WangLe1321** [comment]
> Please add those minor change as we talk offline, other lgtm

done

**Review by BornChanger — APPROVED** [review]

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
