### PR TITLE
*: Create SECURITY.md

### PR DESCRIPTION
**Pull request by s3nt3**
### What problem does this PR solve?

Announce the way and specifications for users to submit vulnerabilities to the tidb security team through Github-Security-Policy.

### What is changed and how does it work?

Refer to the steps mentioned in [add a security policy to your repository](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) to create SECURITY.md.

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by KanShiori** [comment]
LGTM

**Review by july2993 — APPROVED** [review]

**Review by july2993 — COMMENTED** [review]
do we need to add a link to this at README.md?

**Comment by s3nt3** [comment]
> do we need to add a link to this at README.md?

It is usually not needed. If a user wants to report a vulnerability, it can be found through the security -> security policy (https://github.com/pingcap/tidb-operator/security/policy) tab.

**Pull request merged**
