### PR TITLE
Skip setting store labels with invalid semver

### LINKED ISSUE #4919: Sync failed when using custom build of tidb with image version that's not in semantic version format
## Bug Report

**What version of Kubernetes are you using?**

1.21

**What version of TiDB Operator are you using?**

v1.4.3

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

ebs

**What's the status of the TiDB cluster pods?**

tidb-operator-controller-manager-69cb5898fb-m8925      1/1     Running            0          24m     10.0.123.153   ip-xx-xx-xx-xx.ec2.internal   <none>           <none>

**What did you do?**

**What did you expect to see?**

**What did you see instead?**
W0306 04:10:54.712785       1 tidb_member_manager.go:1101] parse tidb verson 'd48b6ae1d61a95d9618e64c7fb8479dc6ec6946a' failed, err: Invalid Semantic Version
E0306 04:10:54.712962       1 tidb_cluster_controller.go:133] TidbCluster: tidb-serverless/serverless-cluster, sync failed Invalid Semantic Version, requeuing

### PR DESCRIPTION
**Pull request by sunxiaoguang**
### What problem does this PR solve?

Try to solve custom build tidb image without semver breaking sync
Closes #4919 

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by csuzhangxc — APPROVED** [review]

**Review by KanShiori — APPROVED** [review]

**Comment by sunxiaoguang** [comment]
hm, it's strange that there is always random failures that don't seem to be related.

**Comment by csuzhangxc** [comment]
> hm, it's strange that there is always random failures that don't seem to be related.

both our cases and CI env are not stable enough.

**Pull request merged**
