### PR TITLE
Allow specifying tidb service load balancer IP

### LINKED ISSUE #242: support all internal load balancer description fields
It is easy enough to do

```
tidb.service.type=LoadBalancer
tidb.service.anotations=cloud.google.com/load-balancer-type=Internal
```

However, there are other available fields such as `loadBalancerIP` that are not as easy to add.

https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing

### PR DESCRIPTION
**Pull request by tennix**
Fixes #242 @gregwebs PTAL

### CODE REVIEW

**Comment by gregwebs** [comment]
LGTM. It is possible to want to configure additional fields in the future though, so I am hoping that in the long-term we will come up with techniques to allow more extensibility. I think in this case part of the problem is that the YAML layout for the load balancer is flattened into the spec instead of nested under a key.

**Comment by tennix** [comment]
I think we should only expose the most commonly used fields, the other fields are seldom used, only advanced users need to set those and they should already know how Helm works and hack the templates to satisfy their needs.

**Comment by gregwebs** [comment]
Maintaining a fork is always a little problematic. But perhaps we can try out [tooling that helps with that]( https://www.replicated.com/ship/)

**Comment by gregwebs** [comment]
CI seems to be out of disk

```
failed to watch file "/var/log/pods/d55fd326-0550-11e9-a901-02422767d21a/tidb-operator-e2e/0.log": no space left on device+ tail -5 result.log
```

**Comment by weekface** [comment]
I have rebuild the dind env. You can try it again later.

**Pull request merged**
