### PR TITLE
Support br-federation-manager managing resources in specific-namespace tidb clusters

### PR DESCRIPTION
**Pull request by michaelmdeng**
### What problem does this PR solve?

Our infra setup deploys a given TiDB cluster across multiple k8s clusters, so we use federation to manage br resources across these k8s clusters. Additionally, we deploy multiple of these TiDB clusters in a single k8s cluster across different namespaces -- for ease of deployment/upgrade and least-access, we want to deploy the br-federation-manager control plane independently for each of these TiDB clusters to manage volume backups/restores in separate namespaces.

### What is changed and how does it work?

This PR applies two sets of changes that enable br-federation-manager (bfm) to run in a namespace-scoped way.

1. Support `clusterScoped` in helm charts. When `clusterScoped=false`, charts generate manifests for `Role`s and `RoleBinding`s in the specified namespace rather than `ClusterRole`s and `ClusterRoleBinding`s.
2. Support `clusterScoped` in the bfm executable. When `-cluster-scoped=false`, the manager will listen to changes in br resources only within the specified namespace rather than cluster-wide.

I modeled these changes after how `clusterScoped` is used in the controller-manager [helm charts](https://github.com/pingcap/tidb-operator/blob/8b83a3fbc3d8b028443231fb38e7d031f05a0341/charts/br-federation/templates/controller-manager-rbac.yaml) and [executable](https://github.com/pingcap/tidb-operator/blob/8b83a3fbc3d8b028443231fb38e7d031f05a0341/pkg/controller/dependences.go#L394-L397).

These changes only affect how the control-plane access resources in its namespace and does not affect how bfm manages data-plane resources in other k8s clusters using provided kubeconfig. Managing data-plane resources continues to be done through `.spec.clusters.tcNamespace` in the federation CRDs.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 

Manual testing to set up bfm in a namespace-scoped way on a control plane cluster and validate it attempts to reconcile namespaced br resources and does not attempt to reconcile br resources in other namespaces.

1. Set up a Kubernetes cluster for testing.
2. Apply CRDs

```
cd $TIDB_OPERATOR_REPO
kubectl create -f manifests/crd.yaml
kubectl apply -f manifests/federation-crd.yaml
```

3. Set up two namespaces, one for the bfm control-plane and one other (representing other namespaces for other tidb clusters)

```
apiVersion: v1
kind: Namespace
metadata:
  name: cluster1
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster2
```

4. Set up bfm kubeconfig following directions [here](https://github.com/pingcap/docs-tidb-operator/blob/master/en/deploy-br-federation.md). This can be mocked as we won't be testing managing data-plane resources

5. Build image and install namespace-scoped bfm

```
cd $TIDB_OPERATOR_REPO
make build
cd images/br-federation-manager
docker build -t {bfm-image} .

cd $TIDB_OPERATOR_REPO
helm install --namespace cluster1 br-federation-manager charts/br-federation --set image={bfm-image} --set clusterScoped=false
```

6. Create an empty backup in `cluster1` namespace control plane. 

```
apiVersion: federation.pingcap.com/v1alpha1
kind: VolumeBackup
metadata:
  name: basic-volumebackup
spec: {}
```

7. Validate that deployment attempts to reconcile this backup.

```
...
2023-11-21T16:32:34.313084051Z I1121 16:32:34.312972       1 fed_volume_backup_controller.go:176] VolumeBackup object cluster1/cluster1-volumebackup enqueue
2023-11-21T16:32:34.410123093Z I1121 16:32:34.410044       1 backup_manager.go:53] sync VolumeBackup cluster1/cluster1-volumebackup
2023-11-21T16:32:34.410132551Z I1121 16:32:34.410078       1 backup_manager.go:120] VolumeBackup cluster1/cluster1-volumebackup set status running
2023-11-21T16:32:34.410134801Z I1121 16:32:34.410090       1 fed_volume_backup_controller.go:126] Finished syncing VolumeBackup "cluster1/cluster1-volumebackup" (78.25µs)
...
```

8. Repeat validation for `VolumeRestore` and `VolumeBackupSchedule`

9. Create br resources in other namespace.

```
apiVersion: federation.pingcap.com/v1alpha1
kind: VolumeBackup
metadata:
  name: cluster2-volumebackup
  namespace: cluster2
spec: {}
---
apiVersion: federation.pingcap.com/v1alpha1
kind: VolumeRestore
metadata:
  name: cluster2-volumerestore
  namespace: cluster2
spec: {}
```

10. Validate that bfm does not register those changes and does not attempt to reconcile those resources.

- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by WangLe1321 — APPROVED** [review]
LGTM

**Review by BornChanger — APPROVED** [review]

**Comment by michaelmdeng** [comment]
@BornChanger just pushed a fix to the failing tests, can I get some help rerunning?

**Comment by BornChanger** [comment]
@michaelmdeng please sign the CLA as required.

**Comment by BornChanger** [comment]
image

**Comment by michaelmdeng** [comment]
> @michaelmdeng please sign the CLA as required.

woops, used the wrong email in the commit, should be fixed now

**Review by WangLe1321 — APPROVED** [review]

**Pull request merged**
