### PR TITLE
Directly use CRD in e2e test instead of helm

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve? 

Currently, our test code in e2e/stability is based on helm in managing tidbcluster. As CRD is the only tool recommended to manage tidbcluster after operator 1.1.0 released, I think it is necessary to use CRD instead of helm to manage tidbcluster in test. However, the current OperatorActions is based on the helm and it's hard to revise it as it would both influence the e2e test and stabilty test. 

As @cofyc commented, the XXXAction is overdesigned and in this request we only using function to manage tidbcluster here.

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
I agree to deprecate helm operations, but suggest using plain utility functions. it should not be hard to write logic around kubernetes and our interface or generic interface from the controller-runtime library.

**Comment by cofyc** [comment]
IMO current XXXActions are over-designed and not portable.

**Comment by Yisaer** [comment]
Updated, now we will directly use function to manage crd.

**Pull request merged**
