### PR TITLE
optimize discovery mechanism pd advertise peer url limit

### PR DESCRIPTION
**Pull request by mikechengwei**
### What problem does this PR solve? 
#1366 

### What is changed and how does it work?
Optimize discovery mechanism advertisePeerUrl length limit

### Check List 

Tests 

 - Unit test
 - E2E test

Code changes

 - Has Go code change

Side effects

None

Related changes

None

### Does this PR introduce a user-facing change?:
None

### CODE REVIEW

**Comment by aylei** [comment]
The format of `advertise-peer-url` is determined by `_start_pd.sh.tpl`, so I think this PR would make more sense if the different form of advertised-peer-urls could be configured via public interface. Because `_start_pd_.sh.tpl` is supposed to be an implementation detail of tidb-operator and modification on this file is unexpected.

**Comment by aylei** [comment]
BTW, the deprecating of the `tidb-cluster` helm chart is working in progress, it is better to apply the change to https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/template.go

**Comment by mikechengwei** [comment]
@aylei different form of advertised-peer-urls is a good idea. But now , is  advertised-peer-url prefix format stable, like `${POD_NAME}.${PEER_SERVICE_NAME}.${NAMESPACE}.svc`. Deploy a tikv cluster and external world can  connect to it, it is important advertised-peer-url can custom. Can we  add a common suffix? 
And discovery mechanism pd advertise peer limit url `.` character  must equal to 4 , can we optimize it to less than.

**Pull request closed without merging**
