### PR TITLE
Use mysqlclient image in initcontainer (#3042)

### LINKED ISSUE #3042: tidb-initializer: init container requires docker hub
## Bug Report

**What version of Kubernetes are you using?**
v1.18.3

**What version of TiDB Operator are you using?**
TiDB Operator Version: version.Info{GitVersion:"v1.1.3", GitCommit:"1cf12d67fba0f68dd2e8c2b6744e2f91de8ef3e7", GitTreeState:"clean", BuildDate:"2020-07-27T10:49:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**What's the status of the TiDB cluster pods?**
```
$ kubectl -n databases get po -o wide
NAME                                       READY   STATUS                  RESTARTS   AGE   IP           NODE      NOMINATED NODE   READINESS GATES
default-discovery-545477b5f5-rqd5b         1/1     Running                 0          30m   10.42.5.6    worker3   <none>           <none>
default-pd-0                               1/1     Running                 0          30m   10.42.4.7    worker2   <none>           <none>
default-pd-1                               1/1     Running                 0          30m   10.42.5.7    worker3   <none>           <none>
default-pd-2                               1/1     Running                 1          30m   10.42.3.10   worker1   <none>           <none>
default-tidb-0                             2/2     Running                 0          28m   10.42.5.9    worker3   <none>           <none>
default-tidb-1                             2/2     Running                 0          28m   10.42.4.9    worker2   <none>           <none>
default-tidb-initializer-vvxwp             0/1     Init:ImagePullBackOff   0          30m   10.42.4.6    worker2   <none>           <none>
default-tikv-0                             1/1     Running                 0          29m   10.42.5.8    worker3   <none>           <none>
default-tikv-1                             1/1     Running                 0          29m   10.42.4.8    worker2   <none>           <none>
default-tikv-2                             1/1     Running                 0          29m   10.42.3.11   worker1   <none>           <none>
tidb-controller-manager-8655b6f79b-m8fbj   1/1     Running                 0          32m   10.42.4.5    worker2   <none>           <none>
tidb-scheduler-6654df6f84-pp9bm            2/2     Running                 0          32m   10.42.5.5    worker3   <none>           <none>

```
**What did you do?**
Created a new cluster with the following initializer:

```
apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  name: tidb-initializer
  namespace: databases
spec:
  image: tcr.trioptima.net/docker.io/tnir/mysqlclient
  cluster:
    namespace: databases
    name: default
  initSql: |-
    create database foo;
  # initSqlConfigMap: tidb-initsql
  passwordSecret: tidb-secret

```

**What did you expect to see?**
Successfull tidb initialization.

**What did you see instead?**
Init container failed to pull busybox:1.31.1 since there is a firewall blocking internet access.

` Warning  Failed     24m (x4 over 26m)    kubelet, worker2   Failed to pull image "busybox:1.31.1": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`

The init container image should be configurable or use the same image as the main container which is configurable.

### PR DESCRIPTION
**Pull request by serbaut**
### What problem does this PR solve?

Fixes #3042 

### What is changed and how does it work?

Instead of using a hardcoded busybox image the image used in the mysqlclient is used in the initContainer.

### Check List 

Code changes

 - Has Go code change

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

The initContainer is not mentioned in the docs or example so I guess no user-facing change.

Possibly:

* If you are using tidbinitializer with a customized mysqlclient image that image must include a shell and the `nc` binary.

### CODE REVIEW

**Comment by cofyc** [comment]
@serbaut 
Thanks! btw, please follow the instructions to sign the CLA

**Comment by DanielZhangQD** [comment]
@serbaut Thanks for the contribution!
BTW, did you test the initialization process with your code change?

**Comment by DanielZhangQD** [comment]
@cofyc Could you please help check the chaos test?

**Comment by cofyc** [comment]
> @cofyc Could you please help check the chaos test?

It's not stable right now, maybe fixed in https://github.com/pingcap/tidb-operator/pull/3060.

anyway, it's not a required, can be ignored.

**Comment by serbaut** [comment]
> BTW, did you test the initialization process with your code change?

I tested by running the unit tests, e2e and by manually in a v4.0.3 cluster.

**Pull request merged**
