### PR TITLE
Update DinD image to make it possible to configure HTTP proxies

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 

fixes https://github.com/pingcap/tidb-operator/issues/461

### Check List 

Tests 

Manual test (add detailed scripts or steps below)

configure http proxies in docker config.json

```
    "proxies": {
        "default": {
            "httpProxy": "http://192.168.90.1:1087",
            "httpsProxy": "http://192.168.90.1:1087",
            "noProxy": ".svc,.local,127.0.0.1,0,1,2,3,4,5,6,7,8,9"
        }   
    }
```

propagate http proxies to dind containers

```
export DIND_PROPAGATE_HTTP_PROXY=true
manifests/local-dind/dind-cluster-v1.12.sh up
```

### CODE REVIEW

**Comment by cofyc** [comment]
```
"noProxy": ".svc,.local,127.0.0.1,0,1,2,3,4,5,6,7,8,9"
```

This is used to whitelist all internal k8s domains and local registry (e.g. http://127.0.0.1:5000).

**Comment by AstroProfundis** [comment]
Do we need to add instructions to the [doc](https://github.com/pingcap/tidb-operator/blob/master/docs/local-dind-tutorial.md)?

**Comment by cofyc** [comment]
@AstroProfundis sure, I'd like to add this as an alternative option to `KUBE_REPO_PREFIX` because it works for all blocked images.

**Comment by cofyc** [comment]
@onlymellb I've updated DinD image and tested it on Linux successfully.

**Comment by cofyc** [comment]
@weekface @onlymellb 
I've rebased on the latest master. PTAL again.

**Comment by weekface** [comment]
This pr needs to add a release note? @cofyc

**Pull request merged**
