### PR TITLE
[CRD] add allowPrivilegeEscalation and capabilities to podSecurityContext

### PR DESCRIPTION
**Pull request by wxiaomou**
### What problem does this PR solve?

Fixing issue https://github.com/pingcap/tidb-operator/issues/4851 by adding two fields allowPrivilegeEscalation and capabilities to podSecurityContext. We can set these two parameters in tidb pods' securityContext after this change.
### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by wxiaomou** [comment]
cc: @hanlins

**Comment by hanlins** [comment]
Seems there're some error installing the crd in [tests](https://github.com/pingcap/tidb-operator/actions/runs/4136994754/jobs/7152949708):
```console
error: error validating "manifests/crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.podSecurityContext): unknown field "allowPrivilegeEscalation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.podSecurityContext): unknown field "capabilities" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by hanlins** [comment]
Hi @wxiaomou, maybe try `make crd` instead of manually change the manifest?

**Comment by wxiaomou** [comment]
discussed this offline, this PR is not needed anymore. Thanks @hanlins

**Comment by shaxiaozz** [comment]
Why not merge this parameter?

**Pull request closed without merging**
