### PR TITLE
mapping some short label names to k8s well-known labels

### LINKED ISSUE #4678: shorten some default location labels
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, when use tidb-operator to deploy cluster in cross AZ environment, it's common to set the location-labels like `["topology.kubernetes.io/region", "topology.kubernetes.io/zone", "kubernetes.io/hostname"]`, but long label names may cause performance problems. See https://github.com/tikv/pd/issues/5360 for more details.

**Describe the feature you'd like:**

As we already support mapping `host` to `kubernetes.io/hostname` in:  https://github.com/pingcap/tidb-operator/blob/00002ede5e5b2c811d8bbff4043a4cc7a2a1e2a6/pkg/manager/member/node.go#L35-L39

I think it's also useful to treat `region` and `zone` in the same way:
`region` --> `topology.kubernetes.io/region` and `failure-domain.beta.kubernetes.io/region`(for old k8s version)
`zone ` --> `topology.kubernetes.io/zone` and `failure-domain.beta.kubernetes.io/zone`(for old k8s version)

So user can config  both `zone` or `topology.kubernetes.io/zone`, and the effect is the same.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Support shorten some labels for k8s well-known labels when used in pd's location labels 

Closes #4678

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [x] Manual test 
  - I uses kind to bootstrap a test k8s cluster and use `kubectl label nodes kind-control-plane` to add 2 labels `topology.kubernetes.io/region=us-west-2, topology.kubernetes.io/zone=us-west-2a`(kind itself can add the label `kubernetes.io/hostname=kind-control-plane`), then I add `replicate-labels = ["region", "zone", "host"]` to example/basic/tidb-cluster.yml and use it to start a cluster. After the cluster is started, tidb log contains `[2022/09/14 06:09:15.541 +00:00] [INFO] [http_handler.go:2188] ["update server labels"] [labels="{\"host\":\"kind-control-plane\",\"region\":\"us-west-2\",\"zone\":\"us-west-2a\"}"]`, that show the labels are effective. Label the node with `failure-domain.beta.kubernetes.io/region=us-west-2, failure-domain.beta.kubernetes.io/zone=us-west-2a` has the same effect.
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Allow use shorten label names to refer to some k8s well-known labels when used in pd's location labels 

```

### CODE REVIEW

**Comment by glorv** [comment]
friendly ping @KanShiori @handlerww PTAL

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
PTAL @KanShiori @csuzhangxc this feature is very important for some scenarios. like `stale read`, `multi-region deploy`, and `placement rule`.

**Review by KanShiori — APPROVED** [review]

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
