### PR TITLE
Update google-kubernetes-tutorial.md

### PR DESCRIPTION
**Pull request by c4pt0r**
make stdout peace.

### CODE REVIEW

**Comment by c4pt0r** [comment]
@gregwebs PTAL

**Comment by gregwebs** [comment]
I think we would still want error output to show up.

``` shell
➜  tidb-operator git:(master) kubectl -n tidb port-forward demo-tidb-0 4000:4000 &>/dev/null &                                                                                                               
[1] 22770
[1]  + 22770 exit 1     kubectl -n tidb port-forward demo-tidb-0 4000:4000 &> /dev/null                                                                                                                            
➜  tidb-operator git:(master) kubectl -n tidb port-forward demo-tidb-0 4000:4000 >/dev/null &                                                                                                                
[1] 22894
error: the server doesn't have a resource type "pods"                                                                                                                                                              
[1]  + 22894 exit 1     kubectl -n tidb port-forward demo-tidb-0 4000:4000 > /dev/null
```

**Pull request merged**
