### PR TITLE
Add `--comments` to READMEs

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?
To stop the MySQL client from stripping TiDB specific comments (`/*T! ... */`) we need to add `--comments`

### Tests

- [x] No code 

### Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
@dveeden Thanks for submitting the PR.
Could you please help explain why would you like to add that parameter?
What's the detailed benefit to enable it?

**Comment by dveeden** [comment]
> @dveeden Thanks for submitting the PR.
> Could you please help explain why would you like to add that parameter?
> What's the detailed benefit to enable it?

```
$ mysql -h 127.0.0.1 -P 4000 -u root -e "SELECT 'This is' /*T! , ' why' */"
+---------+
| This is |
+---------+
| This is |
+---------+
$ mysql -h 127.0.0.1 -P 4000 -u root --comments -e "SELECT 'This is' /*T! , ' why' */"
+---------+------+
| This is | why  |
+---------+------+
| This is |  why |
+---------+------+
```

This style of comments is used in the `SHOW CREATE TABLE` output etc.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by KanShiori — APPROVED** [review]
LGTM

**Pull request merged**
