### PR TITLE
add more error info for controllers

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
Fix https://github.com/pingcap/tidb-operator/issues/1936

### What is changed and how does it work?
Replace all `fmt.Errorf` in `utilruntime.HandleError` with `pingacp/errors.Errorf`.

### Check List 

Tests 

 - Unit test
 - E2E test

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by lichunzhu** [comment]
@aylei Does this PR meet your expectations?

**Comment by cofyc** [comment]
can you paste some examples?

**Comment by lichunzhu** [comment]
The error stack info will be shown like this:
```log
E0702 03:52:43.608254       1 tidb_cluster_controller.go:300] TidbCluster: default/basic, sync failed TidbCluster: [default/basic], waiting for TiKV cluster running, requeuing
github.com/pingcap/tidb-operator/pkg/controller/tidbcluster.(*Controller).processNextWorkItem
        github.com/pingcap/tidb-operator@/pkg/controller/tidbcluster/tidb_cluster_controller.go:300
github.com/pingcap/tidb-operator/pkg/controller/tidbcluster.(*Controller).worker
        github.com/pingcap/tidb-operator@/pkg/controller/tidbcluster/tidb_cluster_controller.go:283
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88
runtime.goexit
        runtime/asm_amd64.s:1357
I0702 03:52:43.743274       1 tidb_cluster_controller.go:313] Finished syncing TidbCluster "default/basic" (130.691ms)
I0702 03:52:43.743326       1 tidb_cluster_controller.go:298] TidbCluster: default/basic, still need sync: TidbCluster: [default/basic], waiting for TiKV cluster running, requeuing
```

**Comment by cofyc** [comment]
the stack shows the stack of function calls, but it's not useful in our scenarios because it does not show where the error happens (see the goal of the issue #1936).
I think it's not possible to know where the error happens unless the returned error contains the context information.
Instead of using the `pingacp/errors.Errorf` function, maybe we should improve the error message in the controller, e.g. adding the function prefix (`xxxx: failed to ....`)

**Comment by cofyc** [comment]
#1936 does have specific goals, we can improve the error messages in our core logic first:

- pd_member_manager.go
- tikv_member_manager.go
- tidb_member_manager.go
- tiflash_member_manager.go

For example:

the error in https://github.com/pingcap/tidb-operator/issues/1936#issue-582115776 may be returned here:

https://github.com/pingcap/tidb-operator/blob/60cf7d493eb056fd7668a042f46ee7b974b73480/pkg/manager/member/tiflash_member_manager.go#L784-L787

the raw error returned by `client-go` is propagated to the outside controller and printed. we don't know where the error is generated, however, we can change this code to

```
        pod, err := tfmm.podLister.Pods(ns).Get(podName)
        if err != nil {
            return setCount, fmt.Errorf("setStoreLabelsForTiFlash: failed to get pod for store %d, error: %v ", status.ID, err)
        }
```

**Comment by aylei** [comment]
Can we annotate the error at the first place (the bottom of error stack in our code), and print the stack trace in the `processNextWorkItem` logic?

**Comment by cofyc** [comment]
> Can we annotate the error at the first place (the bottom of error stack in our code), and print the stack trace in the `processNextWorkItem` logic?

this will work but the stack spans multiple lines and errors are common in our operator. I'm afraid that might be a lot of log output.

**Comment by cofyc** [comment]
To sum up, there are two options:

1. add a specific descriptive message and an optional prefix in the error message, then users can know where the error is generated by searching the message/function in the code
2. annotate with the stack information when the error is generated, then users can know where the error is generated from the stack

I would prefer option 1 for most errors as it prints only one line message. Because the reconciliation controller retries on the error, and API errors or some objects are not synced yet are common in the operator.

option 2 is suitable for fatal errors and the trace in the stack is important in diagnosing the logic bug.

What do you think?

**Comment by aylei** [comment]
> To sum up, there are two options:
> 
> 1. add a specific descriptive message and an optional function prefix in the error message, then users can know where the error is generated by searching the message/function in the code
> 2. annotate with the stack information when the error is generated, then users can know where the error is generated from the stack
> 
> I would prefer option 1 for most errors in the operator as it prints only one line message. Because the reconciliation controller retries on the error, and API errors or some objects are not synced yet are common in the operator.
> 
> option 2 is suitable for fatal errors and when the trace in the stack is important in diagnosing the logic bug.
> 
> What do you think?

Thanks for the conclusion. IMO option 1 would be generally better.

**Comment by cofyc** [comment]
@lichunzhu can you update this PR to use option 1?

**Comment by lichunzhu** [comment]
> @lichunzhu can you update this PR to use option 1?

OK

**Comment by cofyc** [comment]
cc @aylei @Yisaer @DanielZhangQD @weekface PTAL

**Comment by cofyc** [comment]
@lichunzhu can you also update the title of the PR?

**Comment by lichunzhu** [comment]
emmm, I have more info for this PR, I will open another one.

**Pull request merged**
