### PR TITLE
update helm version to the 3.11.0

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

### What problem does this PR solve?
update helm to the latest: 3.11.0

### CODE REVIEW

**Review by csuzhangxc — APPROVED** [review]

**Review by KanShiori — APPROVED** [review]

**Comment by yanggangtony** [comment]
@csuzhangxc 
thanks for review.


Is that ok to do next steps?
charts/tidb-drainer/Chart.yaml
charts/tidb-lightning/Chart.yaml
charts/tikv-importer/Chart.yaml

change the above file 's content from "version: dev" to "version: v1-canary"?

**Pull request merged**
