### PR TITLE
Add unit test for Auto-scaling Util

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve? 
Add unit test for auto-scaling util

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
Most test functions can be rewritten in [table-driven style](https://github.com/golang/go/wiki/TableDrivenTests). This is recommended if a test contains multiple sub-tests because in table-driven style each sub-test is independent and validation code only needs to be written once.

**Comment by Yisaer** [comment]
> table-driven style

Thanks for reminding. I would change to it soon.

**Comment by Yisaer** [comment]
@cofyc @DanielZhangQD  PTAL

**Pull request merged**
