### PR TITLE
Fix PVC resize in multiple PVC setting

### LINKED ISSUE #3851: TiDB Operator tries to resize the PVCs when multiple PVCs are configured for the components
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Deploy tc as below:
```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: t2
spec:
  configUpdateStrategy: RollingUpdate
  discovery: {}
  enablePVReclaim: false
  imagePullPolicy: IfNotPresent
  pd:
    affinity: {}
    baseImage: pingcap/pd
    config:
      dashboard:
        internal-proxy: true
      replication:
        location-labels:
        - region
        - zone
        - rack
        - host
      log:
        file:
          filename: /var/log/pdlog/pd.log
        level: "warn"
      schedule:
        enable-cross-table-merge: true
    storageVolumes:
      - name: log
        storageSize: "2Gi"
        mountPath: "/var/log/pdlog"
    imagePullPolicy: IfNotPresent
    maxFailoverCount: 3
    replicas: 1
    requests:
      storage: 1Gi
    storageClassName: local-storage
  pvReclaimPolicy: Delete
  schedulerName: default-scheduler
  services:
  - name: pd
    type: ClusterIP
  ticdc:
    baseImage: pingcap/ticdc
    replicas: 1
  tidb:
    affinity: {}
    baseImage: pingcap/tidb
    config:
      log:
        file:
          filename: /var/log/tidblog/tidb.log
        level: "warn"
    storageVolumes:
      - name: log
        storageSize: "2Gi"
        mountPath: "/var/log/tidblog"
    imagePullPolicy: IfNotPresent
    maxFailoverCount: 3
    replicas: 1
    separateSlowLog: true
    service:
      type: ClusterIP
    slowLogTailer:
      image: busybox:1.26.2
      imagePullPolicy: IfNotPresent
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 5Mi
  tiflash:
    baseImage: pingcap/tiflash
    config:
      config: |
        [logger]
          count = 5
          errorlog = "/data0/logs/error.log"
    maxFailoverCount: 3
    replicas: 1
    storageClaims:
    - resources:
        requests:
          storage: 10Gi
      storageClassName: local-storage
    - resources:
        requests:
          storage: 10Gi
      storageClassName: local-storage
  tikv:
    affinity: {}
    baseImage: pingcap/tikv
    config:
      storage:
        reserve-space: "0MB"
      rocksdb:
        wal-dir: "/data_sbi/tikv/wal"
        info-log-dir: "/data_sbk/"
      raftdb:
        info-log-dir: "/data_sbj/"
    storageVolumes:
      - name: wal
        storageSize: "2Gi"
        mountPath: "/data_sbi"
      - name: rocks
        storageSize: "2Gi"
        mountPath: "/data_sbk/"
      - name: raft
        storageSize: "2Gi"
        mountPath: "/data_sbj/"
    imagePullPolicy: IfNotPresent
    maxFailoverCount: 3
    replicas: 1
    requests:
      storage: 10Gi
    storageClassName: local-storage
  tlsCluster: {}
  version: v4.0.8
```
**What did you expect to see?**

**What did you see instead?**
The following logs are reported in the tidb-controller-manager without any change to the tc:
```
W0312 09:24:18.708276       1 pvc_resizer.go:203] PVC canary/pd-log-t2-pd-0/ storage request cannot be shrunk (2Gi to 1Gi), skipped
W0312 09:24:18.708387       1 pvc_resizer.go:194] Storage Class "local-storage" used by PVC canary/tikv-wal-t2-tikv-0 does not support volume expansion, skipped
W0312 09:24:18.708409       1 pvc_resizer.go:194] Storage Class "local-storage" used by PVC canary/tikv-rocks-t2-tikv-0 does not support volume expansion, skipped
W0312 09:24:18.708419       1 pvc_resizer.go:194] Storage Class "local-storage" used by PVC canary/tikv-raft-t2-tikv-0 does not support volume expansion, skipped
```

### PR DESCRIPTION
**Pull request by dragonly**
### What problem does this PR solve?

Closes #3851 

### What is changed and how does it work?

Check current storage request with the correct field in `tc.spec` for each component.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
    1. deploy tc and dm-cluster
    ```yaml
    apiVersion: pingcap.com/v1alpha1
    kind: TidbCluster
    metadata:
      name: basic
    spec:
      configUpdateStrategy: RollingUpdate
      discovery: {}
      enablePVReclaim: false
      imagePullPolicy: IfNotPresent
      pd:
        affinity: {}
        baseImage: pingcap/pd
        config:
          dashboard:
            internal-proxy: true
          replication:
            location-labels:
            - region
            - zone
            - rack
            - host
          log:
            file:
              filename: /var/log/pdlog/pd.log
            level: "warn"
          schedule:
            enable-cross-table-merge: true
        storageVolumes:
          - name: log
            storageSize: "2Gi"
            mountPath: "/var/log/pdlog"
        imagePullPolicy: IfNotPresent
        maxFailoverCount: 3
        replicas: 1
        requests:
          storage: 1Gi
        # storageClassName: local-storage
      pvReclaimPolicy: Delete
      schedulerName: default-scheduler
      services:
      - name: pd
        type: ClusterIP
      ticdc:
        baseImage: pingcap/ticdc
        replicas: 1
      tidb:
        affinity: {}
        baseImage: pingcap/tidb
        config:
          log:
            file:
              filename: /var/log/tidblog/tidb.log
            level: "warn"
        storageVolumes:
          - name: log
            storageSize: "2Gi"
            mountPath: "/var/log/tidblog"
        imagePullPolicy: IfNotPresent
        maxFailoverCount: 3
        replicas: 1
        separateSlowLog: true
        service:
          type: ClusterIP
        slowLogTailer:
          image: busybox:1.26.2
          imagePullPolicy: IfNotPresent
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 5Mi
      tiflash:
        baseImage: pingcap/tiflash
        config:
          config: |
            [logger]
              count = 5
              errorlog = "/data0/logs/error.log"
        maxFailoverCount: 3
        replicas: 1
        storageClaims:
        - resources:
            requests:
              storage: 10Gi
          # storageClassName: local-storage
        - resources:
            requests:
              storage: 10Gi
          # storageClassName: local-storage
      tikv:
        affinity: {}
        baseImage: pingcap/tikv
        config:
          storage:
            reserve-space: "0MB"
          rocksdb:
            wal-dir: "/data_sbi/tikv/wal"
            info-log-dir: "/data_sbk/"
          raftdb:
            info-log-dir: "/data_sbj/"
        storageVolumes:
          - name: wal
            storageSize: "2Gi"
            mountPath: "/data_sbi"
          - name: rocks
            storageSize: "2Gi"
            mountPath: "/data_sbk/"
          - name: raft
            storageSize: "2Gi"
            mountPath: "/data_sbj/"
        imagePullPolicy: IfNotPresent
        maxFailoverCount: 3
        replicas: 1
        requests:
          storage: 10Gi
        # storageClassName: local-storage
      pump:
        replicas: 1
        config: {}
        requests:
          storage: 1Gi
      tlsCluster: {}
      version: v4.0.8
    ---
    apiVersion: pingcap.com/v1alpha1
    kind: DMCluster
    metadata:
      name: basic
    spec:
      version: v2.0.0
      discovery:
        address: "http://basic-discovery:10261"
      master:
        baseImage: pingcap/dm
        replicas: 1
        storageSize: "1Gi"
        requests: {}
        config: {}
      worker:
        baseImage: pingcap/dm
        replicas: 1
        storageSize: "1Gi"
        requests: {}
        config: {}
    ```

    2. `kubectl get pod`
    ```
    NAME                                       READY   STATUS    RESTARTS   AGE
    basic-discovery-59c77754b4-5zjn6           1/1     Running   0          2d22h
    basic-dm-master-0                          1/1     Running   0          105s
    basic-dm-worker-0                          1/1     Running   0          80s
    basic-pd-0                                 1/1     Running   0          2d22h
    basic-pump-0                               1/1     Running   0          77m
    basic-ticdc-0                              1/1     Running   0          2d22h
    basic-tidb-0                               2/2     Running   0          76m
    basic-tiflash-0                            4/4     Running   0          2d22h
    basic-tikv-0                               1/1     Running   0          2d22h
    ```

    3. check `tidb-controller-manager` log, and grep for `pvc_resizer.go`, find that the size are in sync
    ```
    I0315 10:03:01.745418       1 pvc_resizer.go:265] PVC pingcap/dm-master-basic-dm-master-0 storage request is already 1Gi, skipped
    I0315 10:03:01.745473       1 pvc_resizer.go:265] PVC pingcap/dm-worker-basic-dm-worker-0 storage request is already 1Gi, skipped
    I0315 10:03:02.537422       1 pvc_resizer.go:265] PVC pingcap/pd-basic-pd-0 storage request is already 1Gi, skipped
    I0315 10:03:02.537442       1 pvc_resizer.go:265] PVC pingcap/pd-log-basic-pd-0 storage request is already 2Gi, skipped
    I0315 10:03:02.537516       1 pvc_resizer.go:265] PVC pingcap/tikv-raft-basic-tikv-0 storage request is already 2Gi, skipped
    I0315 10:03:02.537554       1 pvc_resizer.go:265] PVC pingcap/tikv-basic-tikv-0 storage request is already 10Gi, skipped
    I0315 10:03:02.537583       1 pvc_resizer.go:265] PVC pingcap/tikv-wal-basic-tikv-0 storage request is already 2Gi, skipped
    I0315 10:03:02.537603       1 pvc_resizer.go:265] PVC pingcap/tikv-rocks-basic-tikv-0 storage request is already 2Gi, skipped
    I0315 10:03:02.537644       1 pvc_resizer.go:265] PVC pingcap/tikv-rocks-basic-tikv-0 storage request is already 2Gi, skipped
    I0315 10:03:02.537676       1 pvc_resizer.go:265] PVC pingcap/tikv-raft-basic-tikv-0 storage request is already 2Gi, skipped
    I0315 10:03:02.537694       1 pvc_resizer.go:265] PVC pingcap/tikv-basic-tikv-0 storage request is already 10Gi, skipped
    I0315 10:03:02.537709       1 pvc_resizer.go:265] PVC pingcap/tikv-wal-basic-tikv-0 storage request is already 2Gi, skipped
    I0315 10:03:02.537870       1 pvc_resizer.go:265] PVC pingcap/tikv-raft-basic-tikv-0 storage request is already 2Gi, skipped
    I0315 10:03:02.538222       1 pvc_resizer.go:265] PVC pingcap/tikv-basic-tikv-0 storage request is already 10Gi, skipped
    I0315 10:03:02.538274       1 pvc_resizer.go:265] PVC pingcap/tikv-wal-basic-tikv-0 storage request is already 2Gi, skipped
    I0315 10:03:02.538280       1 pvc_resizer.go:265] PVC pingcap/tikv-rocks-basic-tikv-0 storage request is already 2Gi, skipped
    ```
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Fix the issue that multiple PVC is treated wrong in PVC resizer.
```

### CODE REVIEW

**Review by july2993 — APPROVED** [review]

**Review by handlerww — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
@dragonly Sorry for the late review, some comments here:

1. PVCs for TiDB are not considered
2. Duplicate code here https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/pvc_resizer.go#L210-L216
3. The logs for the test example in the PR description do not include TiFlash and Pump, they do work as expected, right?
And what about the volume expansion and shrink operations?

**Comment by dragonly** [comment]
@DanielZhangQD 
Will cover these in a following PR:
1. PVCs for TiDB
2. remove duplicated code
3. I will re-deploy and check for that

**Pull request merged**
