### PR TITLE
allow porting labels when initiating backup/restore member

### PR DESCRIPTION
**Pull request by oliviachenairbnb**
### What problem does this PR solve?

iam role cannot be used during backup process
### What is changed and how does it work?

allow porting labels when initiating backup/restore member
### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by BornChanger** [comment]
@oliviachenairbnb Please assign the CLA form.

**Review by WangLe1321 — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]

**Pull request closed without merging**
