### PR TITLE
update instance type for tikv

### PR DESCRIPTION
**Pull request by DanielZhangQD**
### What problem does this PR solve? 
Update instance type for tikv since we do not recommend to use local SSD anymore.
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
@lichunzhu @lonng PTAL again, updated after discussion with TiKV team.

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by lonng — APPROVED** [review]

**Pull request merged**
