### PR TITLE
Add trap to create a path when BR container exit

### LINKED ISSUE #5430: Support to terminate sidecars in BR job
## Feature Request

**Is your feature request related to a problem? Please describe:**

If we injected sidecar into current br pods, it will block the job from completing since the sidecar is still running.  
**Describe the feature you'd like:**

Add a signal to notify the sidecar to exit.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by wxiaomou**
### What problem does this PR solve?

Closes #5430

### What is changed and how does it work?

Create a path when the main container exits, the sidecar can check the path once it shows up it can exit. 
### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by WangLe1321 — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]

**Comment by BornChanger** [comment]
/cherry-pick-release-1.5

**Pull request merged**
