### PR TITLE
[BR] Remove k8s cluster name from backup/init pod names

### LINKED ISSUE #5386: ebs br: remove the cluster name from the name of scheduled backup pod
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

As the title.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by nkg-**
### What problem does this PR solve?
This PR mirrors the solution done for restore pods in https://github.com/pingcap/tidb-operator/pull/5318.  

There is a [63 character limit](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names) for k8s pod names. The backup_pod_name follows the schema fed-{backup_name}-{k8s_cluster_name}. This is also used as a prefix to the init pod. This can be pretty long, and likely (it did for us, when we used backup_name like "backup") to hit the character limit. While backup_names and tidb cluster names are easily updated, k8s cluster names are hard to change. And can be long. Real world example - m-tidb-test-a-ea1-us. This PR attempts to shorten the pod names.

Close #5386 

### What is changed and how does it work?
This PR removes the k8s cluster name from the backup and init pod names. Its fine, since these pods operate in different physical k8s clusters. And don't need to be unique across k8s clusters. For example - For heterogeneous tidb clusters, tidb, tikv, pd names are already duplicate across k8s clusters.

Since backup names are not unique anymore, some minor changes.
* Remove usage of backup name to in a map. And use k8s cluster name instead.
* Add k8s cluster name in logs.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by nkg-** [comment]
PTAL @BornChanger

**Review by WangLe1321 — APPROVED** [review]

**Pull request merged**
