### PR TITLE
Allow porting labels to restore pod

### PR DESCRIPTION
**Pull request by oliviachenairbnb**
Allow porting labels to restore pod
### What problem does this PR solve?

Allow porting labels to restore pod
### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@WangLe1321 PTAL

**Review by BornChanger — APPROVED** [review]
lgtm

**Review by WangLe1321 — APPROVED** [review]

**Comment by nkg-** [comment]
Linking blame PR - https://github.com/pingcap/tidb-operator/pull/5247

**Pull request merged**
