### PR TITLE
Replace controller.Int32Ptr with k8s.io/utils/pointer.Int32Ptr (#2841)

### LINKED ISSUE #2836: replace controller.Int32Ptr with pointer.Int32Ptr
remove `controller.Int32Ptr` in `pkg/controller/controller_utils.go`

https://github.com/pingcap/tidb-operator/blob/d47a6a3b327b6dacbd4f590e793389e98d5ccbeb/pkg/controller/controller_utils.go#L372-L375

use [`k8s.io/utils/pointer.Int32Ptr`](https://pkg.go.dev/k8s.io/utils/pointer?tab=doc#Int32Ptr) instead.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #2841 to release-1.1

---

### What problem does this PR solve? 
Resolve #2836 

### What is changed and how does it work?
Replace controller.Int32Ptr with k8s.io/utils/pointer.Int32Ptr

### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
@lichunzhu can you cherry-pick it manually? the refactor PR #2841 changed the code which only goes into v1.2, so the automatic cherry-picked PR has conflicts in release-1.1.

**Comment by lichunzhu** [comment]
> @lichunzhu can you cherry-pick it manually? the refactor PR #2841 changed the code which only goes into v1.2, so the automatic cherry-picked PR has conflicts in release-1.1.

okay

**Comment by cofyc** [comment]
I deleted the file `tikv_group_member_manager.go`, maybe we can resolve the conflicts on the GitHub website. We can see if the CI can pass now.

**Comment by cofyc** [comment]
it seems all goes well

**Pull request merged**
