### PR TITLE
Fix backup data compare logic

### PR DESCRIPTION
**Pull request by weekface**
### What problem does this PR solve? 

This pr fixes:
- backup correct validation: count all tables in the cluster
- move `test` database out of binlog `ignoreSchemas`

### Check List 

Tests 

 - E2E test
 - Stability test

Code changes

 - Has Go code change

Side effects

Related changes

### CODE REVIEW

**Comment by shuijing198799** [comment]
LGTM

**Comment by weekface** [comment]
This pr was merged without e2e passed. @tennix

**Comment by tennix** [comment]
Sorry, I forgot to check this when merging PR. Maybe we should still make passing e2e test a must step?

**Comment by weekface** [comment]
Yes, it should be a must step.

**Pull request merged**
