### PR TITLE
fix: minreadyseconds for last TiKV

### LINKED ISSUE #5501: minReadySeconds does not work for the last upgrade tikv
## Bug Report

**What version of Kubernetes are you using?**
1.16

**What version of TiDB Operator are you using?**
1.3.8+

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
does not matter

**What's the status of the TiDB cluster pods?**
does not matter

**What did you do?**
trigger an upgrade for tikv with annotation ~~"annoKeyTiDBMinReadySeconds"~~  annoKeyTiKVMinReadySeconds configured

**What did you expect to see?**
for the last tikv, it should still wait ~~annoKeyTiDBMinReadySeconds~~ annoKeyTiKVMinReadySeconds before evict-leader-scheduler deleted

**What did you see instead?**
once the last tikv ready (as a pod), the evict-leader-scheduler for it got deleted, then the last tikv start to receive region leaders.

### PR DESCRIPTION
**Pull request by wangz1x**
### What problem does this PR solve?

Closes #5501 

### What is changed and how does it work?

Check whether the last TiKV pod is available before end evict leader.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 
1. Modify the basic tidb-cluster, set `replicas` for TiKV to `2`, and add annotation `tidb.pingcap.com/tikv-min-ready-seconds: "300"`.
2. Deploy the operator and the modified basic tidb-cluster.
3. Once all things ready, trigger an upgrade for TiKV.

```
I0207 05:57:42.942954       1 tidb_cluster_controller.go:142] TidbCluster: default/basic, still need sync: tidbcluster: [default/basic]'s upgraded tikv pod: [basic-tikv-1] is not available, last transition time is 2024-02-07 05:57:42 +0000 UTC, requeuing
...
I0207 06:02:38.460404       1 tidb_cluster_controller.go:142] TidbCluster: default/basic, still need sync: tidbcluster: [default/basic]'s upgraded tikv pod: [basic-tikv-1] is not available, last transition time is 2024-02-07 05:57:42 +0000 UTC, requeuing
I0207 06:03:08.473673       1 pdapi.go:588] call DELETE method: http://basic-pd.default:2379/pd/api/v1/schedulers/evict-leader-scheduler-1 success
I0207 06:03:08.481605       1 tikv_upgrader.go:515] endEvictLeaderbyStoreID: end evict leader for store: 1 of default/basic successfully
I0207 06:03:08.482320       1 tikv_upgrader.go:386] endEvictLeader: end evict leader: 1, default/basic-tikv-1 successfully
I0207 06:03:08.497112       1 pod_control.go:90] Pod: [default/basic-tikv-1] updated successfully, : [default/basic]
...
I0207 06:03:14.588726       1 tidb_cluster_controller.go:142] TidbCluster: default/basic, still need sync: tidbcluster: [default/basic]'s upgraded tikv pod: [basic-tikv-0] is not ready, requeuing
...
I0207 06:07:38.453695       1 tidb_cluster_controller.go:142] TidbCluster: default/basic, still need sync: tidbcluster: [default/basic]'s upgraded tikv pod: [basic-tikv-0] is not available, last transition time is 2024-02-07 06:03:15 +0000 UTC, requeuing
I0207 06:08:08.466089       1 tidb_cluster_controller.go:142] TidbCluster: default/basic, still need sync: tidbcluster: [default/basic]'s upgraded tikv pod: [basic-tikv-0] is not available, last transition time is 2024-02-07 06:03:15 +0000 UTC, requeuing
I0207 06:08:38.464321       1 pdapi.go:588] call DELETE method: http://basic-pd.default:2379/pd/api/v1/schedulers/evict-leader-scheduler-2 success
I0207 06:08:38.467645       1 tikv_upgrader.go:515] endEvictLeaderbyStoreID: end evict leader for store: 2 of default/basic successfully
I0207 06:08:38.468944       1 tikv_upgrader.go:425] tikv: no evict leader scheduler exists for default/basic
```

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by csuzhangxc — APPROVED** [review]

**Comment by csuzhangxc** [comment]
@wangz1x Do you expect this PR to be included in v1.5.x?

**Comment by wangz1x** [comment]
@csuzhangxc  Sure, that would be great

**Pull request merged**
