### PR TITLE
e2e: use controller.GuaranteedUpdate to retry on version conflict

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/2188/tests

```
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/serial.go:133
Jan 9 06:33:17.701: Unexpected error:
<*errors.StatusError | 0xc0005b2320>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on tidbclusters.pingcap.com \"deploy\": the object has been modified; please apply your changes to the latest version and try again",
Reason: "Conflict",
Details: {Name: "deploy", Group: "pingcap.com", Kind: "tidbclusters", UID: "", Causes: nil, RetryAfterSeconds: 0},
Code: 409,
},
}
Operation cannot be fulfilled on tidbclusters.pingcap.com "deploy": the object has been modified; please apply your changes to the latest version and try again
occurred
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/serial.go:233
```

### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
it's strange that this test fails with `no matches for kind "TidbCluster" in version "pingcap.com/v1alpha1"` after this change frequently...

**Comment by aylei** [comment]
@cofyc After reading the code, I figure out the reason:

- `controller-runtime/client` discovers the group resources on initialization;
- e2e test will deploy operator and CRDs first, so the first spec runs in serial test will get a `genericCli` that has `tidbcluster.pingcap.com` discovered;
- however, after each spec in serial test, the operator and CRDs will be deleted;
- subsequent specs creates `genericCli` when CRDs has been deleted, causing the error you see in e2e;
- we cannot see the same issue in non-serial test, because we do not delete CRDs there;
- we cannot reproduce this locally by running a single spec, because the CRDs is not get deleted when `genericCli` of the first spec is created;

**Comment by aylei** [comment]
https://github.com/pingcap/tidb-operator/issues/1551

**Pull request merged**
