### PR TITLE
Remove unreachable code

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
Remove unreachable code
### What is changed and how does it work?
Remove unreachable code

### Check List 

Tests 

 - No code

Code changes

 - Has Go code change

Side effects

None

Related changes

None

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
test-pull-e2e-kind

**Comment by AstroProfundis** [comment]
Are you sure to exit with status code 0 on error?

**Comment by hi-rustin** [comment]
```go
// Fatal is equivalent to Print() followed by a call to os.Exit(1).
func Fatal(v ...interface{}) {
	std.Output(2, fmt.Sprint(v...))
	os.Exit(1)
}
```

**Pull request closed without merging**
