### PR TITLE
refactor so that using the PD API avoids unnecessary imports

### PR DESCRIPTION
**Pull request by gregwebs**
The PD API no longer imports Kubernetes and the CRD.

In the create-statefulset-immediately PR this reduced the new wait-for-pd binary
by ~20M

Tests 

- Existing tests pass

Code changes

 - Has Go code change

### Does this PR introduce a user-facing change?:

No

### CODE REVIEW

**Comment by tennix** [comment]
image
I recompile all the binaries and didn't see the size reduce.

**Comment by gregwebs** [comment]
@tennix the size reduction can only be seen on the create-statefulset-immediately PR for the wait-for-pd binary. It was requested that I make this a separate PR. We could use this same technique for the discovery service and see it there also.

**Comment by tennix** [comment]
@weekface PTAL

**Comment by weekface** [comment]
the `pkg/apis` is the directory for [K8s apis](https://github.com/kubernetes/kubernetes/tree/master/pkg/apis), so it is not a good idea to put pdapis here.

**Comment by gregwebs** [comment]
What directory should it be placed it? @weekface

**Comment by weekface** [comment]
Any other directories other than `pkg/apis` are fine, for example: `pkg/pdapi`.

**Comment by gregwebs** [comment]
@weekface okay, directories are moved. If you come up with a better idea feel free to move or name them something else. `rg -l -i 'pkg/apis/pdapi' | xargs -i@ sed -i 's|pkg/apis/pdapi|pkg/pdapi|g' @`

**Comment by weekface** [comment]
@onlymellb @cofyc @xiaojingchen PTAL

**Pull request merged**
