### PR TITLE
Bump operator to v1.1.8 and tidb components to v4.0.9

### PR DESCRIPTION
**Pull request by dragonly**
### What problem does this PR solve?

Bump operator to v1.1.8 and tidb components to v4.0.9

### What is changed and how does it work?

ref #3490 
run script `hack/bump-version.sh`, and correct some comments by hand.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [x] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
NONE
```

### CODE REVIEW

**Comment by dragonly** [comment]
The CI cannot build, because tidb v4.0.9 has not been released yet. Just wait...

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Review by handlerww — APPROVED** [review]
LGTM

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Pull request merged**
