### PR TITLE
Move compatible filterLeaderEvictScheduler in pdapi

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve? 
Move `filterLeaderEvictScheduler` into pdapi function to make `GetEvictLeaderSchedulers` function common used both for PD 3.0.x and 4.0.x

fixes https://github.com/pingcap/tidb-operator/issues/2761

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
revert this change in this PR? https://github.com/pingcap/tidb-operator/pull/2762/files
we can test it with `3.1.1`, `3.1.2`

**Comment by Yisaer** [comment]
@cofyc  This request haven't apply https://github.com/pingcap/tidb-operator/pull/2762/files yet.

**Comment by cofyc** [comment]
we can wait for current e2e job to finish
I mean we can fix the issue and upgrade the version together.

**Comment by Yisaer** [comment]
> we can wait for current e2e job to finish
> I mean we can fix the issue and upgrade the version together once the PR is merged

got it.

**Comment by Yisaer** [comment]
It seems worked.

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6843/pipeline

**Comment by cofyc** [comment]
upgrade the tidb 3 versions and we can merge this PR

**Pull request merged**
