### PR TITLE
Use GenericConfic for pd/tidb/tikv/tiflash/ticdc

### PR DESCRIPTION
**Pull request by july2993**
### What problem does this PR solve? 

Allow passing what's specified by the user and pass them to tidb/tikv/pd/tiflash as toml config file

#### Know issue
For pd, this config item may have a compatibility problem.
It Accepted "true" and "false" string literal before.
After this PR, we will pass it as a string literal to pd if user still doing this.
Screen Shot 2020-09-16 at 7 08 44 PM

### What is changed and how does it work?

Use GenericConfic for tidb/tikv/tiflash/ticdc

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
deploy a cluster set a config item to tidb
```
  tidb:
    baseImage: pingcap/tidb
    replicas: 1
    service:
      type: ClusterIP
    config:
      what-the: "ok"
```
check logs of tidb:
Screen Shot 2020-09-16 at 8 14 04 PM
tidb will just print wrong log for unknow item default.

Code changes

 - Has Go code change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
Allow passing what's specified by the user and pass them to tidb/tikv/pd/tiflash as toml config file
```

### CODE REVIEW

**Comment by lhy1024** [comment]
when will it be merged to master? I just found there is still some missed config.

**Comment by july2993** [comment]
> when will it be merged to master? I just found there is still some missed config.

pls just add fields like before if you need

**Pull request closed without merging**
