### PR TITLE
Monitoring: Integrated kubernetes cluster monitoring in public cloud platform

### PR DESCRIPTION
**Pull request by qiffang**
Signed-off-by: qiffang <947321353@qq.com>

### What problem does this PR solve? 
Integrated k8s cluster monitor to terraform for public cloud platform.

### What is changed and how does it work?
All major changes is in terraform files. It will apply monitoring files after you execute the command `terraform apply`.

### Check List 

Tests 

 - Manual test 
There are monitoring pods in monitoring namespaces

Code changes

 - Has terraform files change

### CODE REVIEW

**Comment by gregwebs** [comment]
Should the downloaded content be deleted?
How do we ensure that there are resources on nodes that are available for this?
Is there a related change to the docs to tell the user about this?

**Comment by gregwebs** [comment]
This is not added in a modular way: a user would have to delete/comment out theses lines in terraform and maybe manually delete the operator. Also, I am not a fan of helm in general, but it is nice to know that I can delete a helm install with `helm del --purge`. How does one delete this?

I think this is available as a helm chart and the user can install it with a single command? It may be better to just add that one line command to the end of the docs for now until we develop a more custom integration for this.

**Comment by qiffang** [comment]
> Should the downloaded content be deleted?
> How do we ensure that there are resources on nodes that are available for this?
> Is there a related change to the docs to tell the user about this?

The downloaded repo is maintained by us, so we can ensure that the resources always exist.
Currently, terraform also use the same way to apply CRD.
```
kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/${var.operator_version}/manifests/crd.yaml
```

**Comment by gregwebs** [comment]
The new terraform is designed to be modular and users should be able to bring their own K8s cluster. So they may already have Prometheus running and this could create a duplicate installation.

I would really like to just add this suggestion to the end of our docs rather than deal with all the complications from including it.

**Comment by jlerche** [comment]
I will second @gregwebs suggestion. At the very least, if it will be added in to the terraform script, it should be included as an optional module. @qiffang @aylei what do you think?

**Comment by qiffang** [comment]
> I will second @gregwebs suggestion. At the very least, if it will be added in to the terraform script, it should be included as an optional module. @qiffang @aylei what do you think?

@tennix, what do you think?

**Comment by tennix** [comment]
Yes, I agree it should be optional, users can enable or disable it.

**Pull request closed without merging**
