### PR TITLE
update tidb-toolkit version

### PR DESCRIPTION
**Pull request by DanielZhangQD**
### What problem does this PR solve? 
update tidb-toolkit version
### What is changed and how does it work?
update tidb-toolkit version
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by Yisaer** [comment]
Do we need update the default version of pd/tikv/tidb in values.yaml and example folder?

**Comment by DanielZhangQD** [comment]
> Do we need update the default version of pd/tikv/tidb in values.yaml and example folder?

They should be updated when we are ready for a new release.

**Pull request merged**
