### PR TITLE
update sync order for the components

### PR DESCRIPTION
**Pull request by DanielZhangQD**
### What problem does this PR solve?

Fix https://github.com/pingcap/tidb-operator/issues/3853
### What is changed and how does it work?

Discussed with the dev team of different components, the order to sync the components should be:
CDC, PD, TiKV, TiFlash/Pump, TiDB
### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [x] Manual test 
  - Deploy TidbCluster with CDC, PD, TiKV, TiFlash, Pump, TiDB, waiting for Pods ready, upgrade the tc, check that the upgrade order is CDC, TiFlash, PD, TiKV, Pump, TiDB
  - Deploy TidbCluster with CDC, PD, TiKV, TiFlash, Pump, TiDB and enable TLS, waiting for Pods ready, upgrade the tc, check that the upgrade order is CDC, TiFlash, PD, TiKV, Pump, TiDB
  - Deploy TidbCluster with PD, TiKV, TiFlash, TiDB, waiting for Pods ready, upgrade the tc, check that the upgrade order is TiFlash, PD, TiKV, TiDB
  - Deploy TidbCluster with PD, TiKV, TiFlash, TiDB and enable TLS, waiting for Pods ready, upgrade the tc, check that the upgrade order is TiFlash, PD, TiKV, TiDB

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
NONE
```

### CODE REVIEW

**Comment by july2993** [comment]
```
ok  	github.com/pingcap/tidb-operator/pkg/features	1.497s	coverage: 0.7% of statements in ./cmd/admission-webhook, ./cmd/backup-manager, ./cmd/backup-manager/app, ./cmd/backup-manager/app/backup, ./cmd/backup-manager/app/clean, ./cmd/backup-manager/app/cmd, ./cmd/backup-manager/app/constants, ./cmd/backup-manager/app/export, ./cmd/backup-manager/app/import, ./cmd/backup-manager/app/restore, ./cmd/backup-manager/app/util, ./cmd/controller-manager, ./cmd/discovery, ./cmd/scheduler, ./cmd/tkctl, ./cmd/to-crdgen, ./pkg/autoscaler, ./pkg/autoscaler/autoscaler, ./pkg/autoscaler/autoscaler/calculate, ./pkg/autoscaler/autoscaler/query, ./pkg/backup, ./pkg/backup/backup, ./pkg/backup/backupschedule, ./pkg/backup/constants, ./pkg/backup/restore, ./pkg/backup/testutils, ./pkg/backup/util, ./pkg/controller, ./pkg/controller/autoscaler, ./pkg/controller/backup, ./pkg/controller/backupschedule, ./pkg/controller/dmcluster, ./pkg/controller/periodicity, ./pkg/controller/restore, ./pkg/controller/tidbcluster, ./pkg/controller/tidbinitializer, ./pkg/controller/tidbmonitor, ./pkg/discovery, ./pkg/discovery/server, ./pkg/dmapi, ./pkg/features, ./pkg/label, ./pkg/manager, ./pkg/manager/member, ./pkg/manager/meta, ./pkg/metrics, ./pkg/monitor, ./pkg/monitor/monitor, ./pkg/pdapi, ./pkg/plugin/admission/install, ./pkg/registry, ./pkg/scheduler, ./pkg/scheduler/predicates, ./pkg/scheduler/server, ./pkg/scheme, ./pkg/tikvapi, ./pkg/to-crdgen/cmd, ./pkg/to-crdgen/cmd/generate, ./pkg/upgrader, ./pkg/util, ./pkg/util/config, ./pkg/util/crypto, ./pkg/util/discovery, ./pkg/util/dmcluster, ./pkg/util/http, ./pkg/util/tidbcluster, ./pkg/util/toml, ./pkg/version, ./pkg/webhook/pod, ./pkg/webhook/statefulset, ./pkg/webhook/strategy, ./pkg/webhook/util, 
# github.com/pingcap/tidb-operator/pkg/manager/member [github.com/pingcap/tidb-operator/pkg/manager/member.test]
Error: pkg/manager/member/ticdc_upgrader_test.go:147:6: unknown field 'Health' in struct literal of type "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1".TiCDCCapture
Error: pkg/manager/member/ticdc_upgrader_test.go:270:7: unknown field 'Health' in struct literal of type "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1".TiCDCCapture
Error: pkg/manager/member/ticdc_upgrader_test.go:274:7: unknown field 'Health' in struct literal of type "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1".TiCDCCapture
ok  	github.com/pingcap/tidb-operator/pkg/label	2.140s	coverage: 0.7% of statements in ./cmd/admission-webhook, ./cmd/backup-manager, ./cmd/backup-manager/app, ./cmd/backup-manager/app/backup, ./cmd/backup-manager/app/clean, ./cmd/backup-manager/app/cmd, ./cmd/backup-manager/app/constants, ./cmd/backup-manager/app/export, ./cmd/backup-manager/app/import, ./cmd/backup-manager/app/restore, ./cmd/backup-manager/app/util, ./cmd/controller-manager, ./cmd/discovery, ./cmd/scheduler, ./cmd/tkctl, ./cmd/to-crdgen, ./pkg/autoscaler, 
```

**Review by july2993 — APPROVED** [review]

**Comment by DanielZhangQD** [comment]
> ```
> ok  	github.com/pingcap/tidb-operator/pkg/features	1.497s	coverage: 0.7% of statements in ./cmd/admission-webhook, ./cmd/backup-manager, ./cmd/backup-manager/app, ./cmd/backup-manager/app/backup, ./cmd/backup-manager/app/clean, ./cmd/backup-manager/app/cmd, ./cmd/backup-manager/app/constants, ./cmd/backup-manager/app/export, ./cmd/backup-manager/app/import, ./cmd/backup-manager/app/restore, ./cmd/backup-manager/app/util, ./cmd/controller-manager, ./cmd/discovery, ./cmd/scheduler, ./cmd/tkctl, ./cmd/to-crdgen, ./pkg/autoscaler, ./pkg/autoscaler/autoscaler, ./pkg/autoscaler/autoscaler/calculate, ./pkg/autoscaler/autoscaler/query, ./pkg/backup, ./pkg/backup/backup, ./pkg/backup/backupschedule, ./pkg/backup/constants, ./pkg/backup/restore, ./pkg/backup/testutils, ./pkg/backup/util, ./pkg/controller, ./pkg/controller/autoscaler, ./pkg/controller/backup, ./pkg/controller/backupschedule, ./pkg/controller/dmcluster, ./pkg/controller/periodicity, ./pkg/controller/restore, ./pkg/controller/tidbcluster, ./pkg/controller/tidbinitializer, ./pkg/controller/tidbmonitor, ./pkg/discovery, ./pkg/discovery/server, ./pkg/dmapi, ./pkg/features, ./pkg/label, ./pkg/manager, ./pkg/manager/member, ./pkg/manager/meta, ./pkg/metrics, ./pkg/monitor, ./pkg/monitor/monitor, ./pkg/pdapi, ./pkg/plugin/admission/install, ./pkg/registry, ./pkg/scheduler, ./pkg/scheduler/predicates, ./pkg/scheduler/server, ./pkg/scheme, ./pkg/tikvapi, ./pkg/to-crdgen/cmd, ./pkg/to-crdgen/cmd/generate, ./pkg/upgrader, ./pkg/util, ./pkg/util/config, ./pkg/util/crypto, ./pkg/util/discovery, ./pkg/util/dmcluster, ./pkg/util/http, ./pkg/util/tidbcluster, ./pkg/util/toml, ./pkg/version, ./pkg/webhook/pod, ./pkg/webhook/statefulset, ./pkg/webhook/strategy, ./pkg/webhook/util, 
> # github.com/pingcap/tidb-operator/pkg/manager/member [github.com/pingcap/tidb-operator/pkg/manager/member.test]
> Error: pkg/manager/member/ticdc_upgrader_test.go:147:6: unknown field 'Health' in struct literal of type "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1".TiCDCCapture
> Error: pkg/manager/member/ticdc_upgrader_test.go:270:7: unknown field 'Health' in struct literal of type "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1".TiCDCCapture
> Error: pkg/manager/member/ticdc_upgrader_test.go:274:7: unknown field 'Health' in struct literal of type "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1".TiCDCCapture
> ok  	github.com/pingcap/tidb-operator/pkg/label	2.140s	coverage: 0.7% of statements in ./cmd/admission-webhook, ./cmd/backup-manager, ./cmd/backup-manager/app, ./cmd/backup-manager/app/backup, ./cmd/backup-manager/app/clean, ./cmd/backup-manager/app/cmd, ./cmd/backup-manager/app/constants, ./cmd/backup-manager/app/export, ./cmd/backup-manager/app/import, ./cmd/backup-manager/app/restore, ./cmd/backup-manager/app/util, ./cmd/controller-manager, ./cmd/discovery, ./cmd/scheduler, ./cmd/tkctl, ./cmd/to-crdgen, ./pkg/autoscaler, 
> ```

@july2993 Thanks, UT fixed.

**Review by handlerww — APPROVED** [review]
LGTM

**Pull request merged**
