### PR TITLE
get TS and use it before full backup using mydumper

### PR DESCRIPTION
**Pull request by weekface**
### What problem does this PR solve? 

This pr fixes: #533 and closes: #540 

- remove --chunk-filesize option
- set --verbose to 3 (info)
- fix stability tests about binlog backup
- get TS before backup

The mydumper output when we change --verbose to 3:
```
** Message: Server version reported as: 5.7.25-TiDB-v3.0.0-rc.1
** Message: Connected to a TiDB server
** Message: Skipping locks because of TiDB
** Message: Set to tidb_snapshot '408711625696608257'
** Message: Started dump at: 2019-05-29 06:25:37
** Message: Written master status
** Message: Thread 1 connected using MySQL connection ID 28
** Message: Thread 1 set to tidb_snapshot '408711625696608257'
** Message: Thread 2 connected using MySQL connection ID 60
** Message: Thread 2 set to tidb_snapshot '408711625696608257'
** Message: Thread 3 connected using MySQL connection ID 29
** Message: Thread 3 set to tidb_snapshot '408711625696608257'
** Message: Thread 4 connected using MySQL connection ID 61
** Message: Thread 4 set to tidb_snapshot '408711625696608257'
** Message: Thread 3 dumping data for `mysql`.`GLOBAL_VARIABLES`
** Message: Non-InnoDB dump complete, unlocking tables
** Message: Thread 2 dumping data for `mysql`.`columns_priv`
** Message: Thread 1 dumping data for `mysql`.`bind_info`
** Message: Thread 4 dumping data for `mysql`.`db`
** Message: Empty table mysql.bind_info
** Message: Thread 1 dumping data for `mysql`.`default_roles`
** Message: Empty table mysql.columns_priv
** Message: Thread 2 dumping data for `mysql`.`gc_delete_range`
** Message: Empty table mysql.db
** Message: Thread 4 dumping data for `mysql`.`gc_delete_range_done`
** Message: Thread 3 dumping data for `mysql`.`help_topic`
** Message: Empty table mysql.gc_delete_range
** Message: Thread 2 dumping data for `mysql`.`role_edges`
** Message: Empty table mysql.gc_delete_range_done
** Message: Thread 4 dumping data for `mysql`.`stats_buckets`
** Message: Empty table mysql.help_topic
** Message: Thread 3 dumping data for `mysql`.`stats_feedback`
** Message: Empty table mysql.role_edges
** Message: Thread 2 dumping data for `mysql`.`stats_histograms`
** Message: Empty table mysql.stats_feedback
** Message: Thread 3 dumping data for `mysql`.`stats_meta`
** Message: Thread 3 dumping data for `mysql`.`stats_top_n`
** Message: Empty table mysql.stats_top_n
** Message: Thread 3 dumping data for `mysql`.`tables_priv`
** Message: Thread 2 dumping data for `mysql`.`tidb`
** Message: Thread 2 dumping data for `mysql`.`user`
** Message: Thread 2 dumping data for `test`.`block_writer`
** Message: Thread 4 dumping data for `test`.`block_writer1`
** Message: Empty table mysql.default_roles
** Message: Thread 1 dumping data for `test`.`block_writer10`
** Message: Thread 4 dumping data for `test`.`block_writer11`
** Message: Thread 2 dumping data for `test`.`block_writer12`
** Message: Thread 1 dumping data for `test`.`block_writer13`
** Message: Empty table mysql.tables_priv
** Message: Thread 3 dumping data for `test`.`block_writer14`
** Message: Thread 4 dumping data for `test`.`block_writer15`
** Message: Thread 2 dumping data for `test`.`block_writer16`
** Message: Thread 1 dumping data for `test`.`block_writer17`
** Message: Thread 3 dumping data for `test`.`block_writer18`
** Message: Thread 4 dumping data for `test`.`block_writer19`
** Message: Thread 4 dumping data for `test`.`block_writer2`
** Message: Thread 3 dumping data for `test`.`block_writer20`
** Message: Thread 2 dumping data for `test`.`block_writer21`
** Message: Thread 4 dumping data for `test`.`block_writer22`
** Message: Thread 2 dumping data for `test`.`block_writer23`
** Message: Thread 3 dumping data for `test`.`block_writer24`
** Message: Thread 1 dumping data for `test`.`block_writer25`
** Message: Thread 4 dumping data for `test`.`block_writer26`
** Message: Thread 3 dumping data for `test`.`block_writer27`
** Message: Thread 2 dumping data for `test`.`block_writer28`
** Message: Thread 1 dumping data for `test`.`block_writer29`
** Message: Thread 4 dumping data for `test`.`block_writer3`
** Message: Thread 3 dumping data for `test`.`block_writer30`
** Message: Thread 2 dumping data for `test`.`block_writer31`
** Message: Thread 1 dumping data for `test`.`block_writer32`
** Message: Thread 4 dumping data for `test`.`block_writer33`
** Message: Thread 2 dumping data for `test`.`block_writer34`
** Message: Thread 4 dumping data for `test`.`block_writer35`
** Message: Thread 3 dumping data for `test`.`block_writer36`
** Message: Thread 2 dumping data for `test`.`block_writer37`
** Message: Thread 4 dumping data for `test`.`block_writer38`
** Message: Thread 1 dumping data for `test`.`block_writer39`
** Message: Thread 3 dumping data for `test`.`block_writer4`
** Message: Thread 2 dumping data for `test`.`block_writer40`
** Message: Thread 4 dumping data for `test`.`block_writer41`
** Message: Thread 1 dumping data for `test`.`block_writer42`
** Message: Thread 3 dumping data for `test`.`block_writer43`
** Message: Thread 2 dumping data for `test`.`block_writer44`
** Message: Thread 4 dumping data for `test`.`block_writer45`
** Message: Thread 1 dumping data for `test`.`block_writer46`
** Message: Thread 2 dumping data for `test`.`block_writer47`
** Message: Thread 4 dumping data for `test`.`block_writer48`
** Message: Thread 3 dumping data for `test`.`block_writer49`
** Message: Thread 2 dumping data for `test`.`block_writer5`
** Message: Thread 4 dumping data for `test`.`block_writer50`
** Message: Thread 1 dumping data for `test`.`block_writer51`
** Message: Thread 3 dumping data for `test`.`block_writer52`
** Message: Thread 2 dumping data for `test`.`block_writer53`
** Message: Thread 2 dumping data for `test`.`block_writer54`
** Message: Thread 3 dumping data for `test`.`block_writer55`
** Message: Thread 4 dumping data for `test`.`block_writer56`
** Message: Thread 3 dumping data for `test`.`block_writer57`
** (mydumper:1): CRITICAL **: Error dumping table (test.block_writer51) data: other error: request to underhook engine failed
** Message: Empty table test.block_writer51
** Message: Thread 1 dumping data for `test`.`block_writer58`
** Message: Thread 2 dumping data for `test`.`block_writer59`
** Message: Thread 4 dumping data for `test`.`block_writer6`
** Message: Thread 3 dumping data for `test`.`block_writer60`
** Message: Thread 1 dumping data for `test`.`block_writer61`
** Message: Thread 2 dumping data for `test`.`block_writer62`
** Message: Thread 4 dumping data for `test`.`block_writer63`
** Message: Thread 3 dumping data for `test`.`block_writer7`
** Message: Thread 1 dumping data for `test`.`block_writer8`
** Message: Thread 1 dumping data for `test`.`block_writer9`
** Message: Thread 2 dumping data for `test`.`testTable`
** Message: Thread 2 dumping schema for `mysql`.`GLOBAL_VARIABLES`
** Message: Thread 2 dumping schema for `mysql`.`bind_info`
** Message: Thread 2 dumping schema for `mysql`.`columns_priv`
** Message: Thread 2 dumping schema for `mysql`.`db`
** Message: Thread 2 dumping schema for `mysql`.`default_roles`
** Message: Thread 2 dumping schema for `mysql`.`gc_delete_range`
** Message: Thread 2 dumping schema for `mysql`.`gc_delete_range_done`
** Message: Thread 2 dumping schema for `mysql`.`help_topic`
** Message: Thread 2 dumping schema for `mysql`.`role_edges`
** Message: Thread 2 dumping schema for `mysql`.`stats_buckets`
** Message: Thread 2 dumping schema for `mysql`.`stats_feedback`
** Message: Thread 2 dumping schema for `mysql`.`stats_histograms`
** Message: Thread 2 dumping schema for `mysql`.`stats_meta`
** Message: Thread 2 dumping schema for `mysql`.`stats_top_n`
** Message: Thread 2 dumping schema for `mysql`.`tables_priv`
** Message: Thread 2 dumping schema for `mysql`.`tidb`
** Message: Thread 2 dumping schema for `mysql`.`user`
** Message: Thread 2 dumping schema for `test`.`block_writer`
** Message: Thread 2 dumping schema for `test`.`block_writer1`
** Message: Thread 2 dumping schema for `test`.`block_writer10`
** Message: Thread 2 dumping schema for `test`.`block_writer11`
** Message: Thread 2 dumping schema for `test`.`block_writer12`
** Message: Thread 2 dumping schema for `test`.`block_writer13`
** Message: Thread 2 dumping schema for `test`.`block_writer14`
** Message: Thread 2 dumping schema for `test`.`block_writer15`
** Message: Thread 2 dumping schema for `test`.`block_writer16`
** Message: Thread 2 dumping schema for `test`.`block_writer17`
** Message: Thread 2 dumping schema for `test`.`block_writer18`
** Message: Thread 2 dumping schema for `test`.`block_writer19`
** Message: Thread 2 dumping schema for `test`.`block_writer2`
** Message: Thread 2 dumping schema for `test`.`block_writer20`
** Message: Thread 2 dumping schema for `test`.`block_writer21`
** Message: Thread 2 dumping schema for `test`.`block_writer22`
** Message: Thread 2 dumping schema for `test`.`block_writer23`
** Message: Thread 2 dumping schema for `test`.`block_writer24`
** Message: Thread 2 dumping schema for `test`.`block_writer25`
** Message: Thread 2 dumping schema for `test`.`block_writer26`
** Message: Thread 2 dumping schema for `test`.`block_writer27`
** Message: Thread 2 dumping schema for `test`.`block_writer28`
** Message: Thread 2 dumping schema for `test`.`block_writer29`
** Message: Thread 2 dumping schema for `test`.`block_writer3`
** Message: Thread 2 dumping schema for `test`.`block_writer30`
** Message: Thread 2 dumping schema for `test`.`block_writer31`
** Message: Thread 2 dumping schema for `test`.`block_writer32`
** Message: Thread 2 dumping schema for `test`.`block_writer33`
** Message: Thread 2 dumping schema for `test`.`block_writer34`
** Message: Thread 2 dumping schema for `test`.`block_writer35`
** Message: Thread 2 dumping schema for `test`.`block_writer36`
** Message: Thread 2 dumping schema for `test`.`block_writer37`
** Message: Thread 2 dumping schema for `test`.`block_writer38`
** Message: Thread 2 dumping schema for `test`.`block_writer39`
** Message: Thread 2 dumping schema for `test`.`block_writer4`
** Message: Thread 2 dumping schema for `test`.`block_writer40`
** Message: Thread 2 dumping schema for `test`.`block_writer41`
** Message: Thread 2 dumping schema for `test`.`block_writer42`
** Message: Thread 2 dumping schema for `test`.`block_writer43`
** Message: Thread 2 dumping schema for `test`.`block_writer44`
** Message: Thread 2 dumping schema for `test`.`block_writer45`
** Message: Thread 2 dumping schema for `test`.`block_writer46`
** Message: Thread 2 dumping schema for `test`.`block_writer47`
** Message: Thread 2 dumping schema for `test`.`block_writer48`
** Message: Thread 2 dumping schema for `test`.`block_writer49`
** Message: Thread 2 dumping schema for `test`.`block_writer5`
** Message: Thread 2 dumping schema for `test`.`block_writer50`
** Message: Thread 2 dumping schema for `test`.`block_writer51`
** Message: Thread 2 dumping schema for `test`.`block_writer52`
** Message: Thread 2 dumping schema for `test`.`block_writer53`
** Message: Thread 2 dumping schema for `test`.`block_writer54`
** Message: Thread 2 dumping schema for `test`.`block_writer55`
** Message: Thread 2 dumping schema for `test`.`block_writer56`
** Message: Thread 2 dumping schema for `test`.`block_writer57`
** Message: Thread 2 dumping schema for `test`.`block_writer58`
** Message: Thread 2 dumping schema for `test`.`block_writer59`
** Message: Thread 2 dumping schema for `test`.`block_writer6`
** Message: Thread 2 dumping schema for `test`.`block_writer60`
** Message: Thread 2 dumping schema for `test`.`block_writer61`
** Message: Thread 2 dumping schema for `test`.`block_writer62`
** Message: Thread 2 dumping schema for `test`.`block_writer63`
** Message: Thread 2 dumping schema for `test`.`block_writer7`
** Message: Thread 2 dumping schema for `test`.`block_writer8`
** Message: Thread 2 dumping schema for `test`.`block_writer9`
** Message: Thread 2 dumping schema for `test`.`testTable`
** Message: Thread 2 shutting down
** Message: Thread 3 shutting down
** Message: Thread 4 shutting down
** Message: Thread 1 shutting down
** Message: Finished dump at: 2019-05-29 06:27:50
```

### Check List 

Tests 

 - E2E test
 - Stability test
 - No code

Code changes

 - Has Helm charts change

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:
 
 ```release-note
get TS and use it before full backup using mydumper
```

### CODE REVIEW

**Comment by shuijing198799** [comment]
LGTM

**Comment by weekface** [comment]
@xiaojingchen @aylei PTAL

**Pull request merged**
