### PR TITLE
Build tools and output to repo's dir instead of GOBIN

### PR DESCRIPTION
**Pull request by KanShiori**
### What problem does this PR solve?

Build tools and output to repo's dir instead of GOBIN. In order not to override global cmd.

### Code changes

- [ ] Has Go code change
- [x] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by KanShiori** [comment]
@csuzhangxc  @DanielZhangQD  PTAL

**Review by csuzhangxc — APPROVED** [review]

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Pull request merged**
