### PR TITLE
Added marketplace product code filter for bastion to avoid selecting AMI from wrong vendor

### LINKED ISSUE #1774: aws bastion module is choosing an AMI that incurs charges
## Bug Report

**What version of TiDB Operator are you using?**
master, 0d40d9c304cac4a2c44e7eadaa30d1ab93236daf

It seems that the owner and filter criteria in deploy/modules/aws/bastion/data.tf are matching an AMI that incurs usage charges.

The list of matching AMIs can be found with this command: `aws ec2 describe-images --owners 679593333241 --region us-west-2 --filter Name=name,Values="CentOS Linux 7 x86_64 HVM EBS *" Name=architecture,Values=x86_64  Name=root-device-type,Values=ebs`

Note that there are 2 marketplace ProductCodeIds in the output:
```
$ aws ec2 describe-images --owners 679593333241 --region us-west-2 --filter Name=name,Values="CentOS Linux 7 x86_64 HVM EBS *" Name=architecture,Values=x86_64  Name=root-device-type,Values=ebs | jq -r '.Images[]|.ProductCodes[]|.ProductCodeId' | sort | uniq
67xglex2rdpaymxh17620nfoy
aw0evgkw8e5c1q413zgy5pjce
```

aw0evgkw8e5c1q413zgy5pjce is the product code we want (https://aws.amazon.com/marketplace/pp?sku=aw0evgkw8e5c1q413zgy5pjce) while 67xglex2rdpaymxh17620nfoy (https://aws.amazon.com/marketplace/pp?sku=67xglex2rdpaymxh17620nfoy) is some other product, provided by another vendor ("Supported Images"), which appears to include an hourly usage fee.

I guess we should make some change to the filtering criteria in deploy/modules/aws/bastion/data.tf so that the correct image is chosen?

### PR DESCRIPTION
**Pull request by kolbe**
### What problem does this PR solve? 
Fixes #1774 

### What is changed and how does it work?
Adds a filter on marketplace Product Code (in addition to existing filters) to make sure the correct product is chosen.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

I simply tested `terraform apply` after applying this change and the correct AMI was chosen (whereas the *incorrect* AMI was being chosen before applying the change).

Code changes

 - Has Terraform scripts change

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by tennix** [comment]
What about other regions?

**Comment by kolbe** [comment]
> What about other regions?

Marketplace product codes are not region-dependent.

```
$ for region in {eu,us}-west-2 ap-southeast-2; do echo "$region"; aws ec2 describe-images --region "$region" --filter Name=product-code,Values=aw0evgkw8e5c1q413zgy5pjce | jq '.Images[]|.Description'; done
eu-west-2
"CentOS Linux 7 x86_64 HVM EBS ENA 1805_01"
"CentOS Linux 7 x86_64 HVM EBS ENA 1901_01"
"CentOS Linux 7 x86_64 HVM EBS ENA 1804_2"
"CentOS Linux 7 x86_64 HVM EBS ENA 1803_01"
"CentOS Linux 7 x86_64 HVM EBS 1708_11.01"
us-west-2
"CentOS Linux 7 x86_64 HVM EBS ENA 1901_01"
"CentOS Linux 7 x86_64 HVM EBS ENA 1803_01"
"CentOS Linux 7 x86_64 HVM EBS ENA 1805_01"
"CentOS Linux 7 x86_64 HVM EBS ENA 1804_2"
"CentOS Linux 7 x86_64 HVM EBS 1708_11.01"
ap-southeast-2
"CentOS Linux 7 x86_64 HVM EBS ENA 1901_01"
"CentOS Linux 7 x86_64 HVM EBS ENA 1804_2"
"CentOS Linux 7 x86_64 HVM EBS 1708_11.01"
"CentOS Linux 7 x86_64 HVM EBS ENA 1805_01"
"CentOS Linux 7 x86_64 HVM EBS ENA 1803_01"
```

**Comment by tennix** [comment]
> > What about other regions?
> 
> Marketplace product codes are not region-dependent.
> 
> ```
> $ for region in {eu,us}-west-2 ap-southeast-2; do echo "$region"; aws ec2 describe-images --region "$region" --filter Name=product-code,Values=aw0evgkw8e5c1q413zgy5pjce | jq '.Images[]|.Description'; done
> eu-west-2
> "CentOS Linux 7 x86_64 HVM EBS ENA 1805_01"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1901_01"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1804_2"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1803_01"
> "CentOS Linux 7 x86_64 HVM EBS 1708_11.01"
> us-west-2
> "CentOS Linux 7 x86_64 HVM EBS ENA 1901_01"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1803_01"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1805_01"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1804_2"
> "CentOS Linux 7 x86_64 HVM EBS 1708_11.01"
> ap-southeast-2
> "CentOS Linux 7 x86_64 HVM EBS ENA 1901_01"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1804_2"
> "CentOS Linux 7 x86_64 HVM EBS 1708_11.01"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1805_01"
> "CentOS Linux 7 x86_64 HVM EBS ENA 1803_01"
> ```

Yeah, I've just verified that too. The change looks good to me.

**Pull request merged**
