### PR TITLE
fix UnjoinedMembers in PD and DM cluster status

### PR DESCRIPTION
**Pull request by dragonly**
### What problem does this PR solve?

ref: #3802

### What is changed and how does it work?

Change PD and DM related code to show correct current `UnjoinedMembers` list.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [ ] E2E test 
- [x] Manual test 
    1. deploy tc with 3 PD, each with an additional PVC, scale to 4, and scale down to 3.
    ```yaml
    apiVersion: pingcap.com/v1alpha1
    kind: TidbCluster
    metadata:
        name: basic
    spec:
        version: v4.0.10
        timezone: UTC
        pvReclaimPolicy: Delete
        configUpdateStrategy: RollingUpdate
        discovery: {}
        pd:
            baseImage: pingcap/pd
            replicas: 3
            requests:
            storage: "1Gi"
            config: {}
            storageVolumes:
                - name: additional
                storageSize: "1Gi"
                mountPath: /mnt
        tikv:
            baseImage: pingcap/tikv
            replicas: 1
            requests:
            storage: "1Gi"
            config: {}
        tidb:
            baseImage: pingcap/tidb
            replicas: 1
            config: {}
    ```
    2. `kubectl get pvc`
    ```
    NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
    pd-additional-basic-pd-0   Bound    pvc-d3174c48-b165-4a2b-95a6-bffc28d538c5   1Gi        RWO            standard       22h
    pd-additional-basic-pd-1   Bound    pvc-0a5019b1-cef2-48d2-929d-64bdf7d99bba   1Gi        RWO            standard       22h
    pd-additional-basic-pd-2   Bound    pvc-4a318448-6abd-4a1d-84e7-3fdc0a5f3738   1Gi        RWO            standard       22h
    pd-additional-basic-pd-3   Bound    pvc-4ee1b4af-745d-4906-89f8-e8dd7f094bb0   1Gi        RWO            standard       4m4s
    pd-basic-pd-0              Bound    pvc-a9c900f8-44ee-4888-b515-3da64272fe68   1Gi        RWO            standard       22h
    pd-basic-pd-1              Bound    pvc-3de3254b-4180-4d1e-aadf-8523d42936b7   1Gi        RWO            standard       22h
    pd-basic-pd-2              Bound    pvc-1e0646c3-bb32-47e6-9cf7-63b826721de8   1Gi        RWO            standard       22h
    pd-basic-pd-3              Bound    pvc-4552b8e8-0a6c-4b37-b438-fa8fd0634f59   1Gi        RWO            standard       4m4s
    tikv-basic-tikv-0          Bound    pvc-14a0fcc2-bca6-48d8-9243-35387f4141cf   1Gi        RWO            standard       22h
    ```
    3. `kubectl get tc`, we can find that the `unjoinedMembers` contains `basic-pd-3`, and the `pvcUIDSet` contains exactly the same PVCs as `pd-basic-pd-3` and `pd-additional-basic-pd-3`
    ```yaml
    unjoinedMembers:
        basic-pd-3:
            createdAt: "2021-03-11T07:02:22Z"
            podName: basic-pd-3
            pvcUIDSet:
                4552b8e8-0a6c-4b37-b438-fa8fd0634f59: {}
                4ee1b4af-745d-4906-89f8-e8dd7f094bb0: {}
    ```

- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Fix `UnjoinedMembers` in PD and DM cluster status.
```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
@dragonly could you please add the test result in the PR description?

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
