### PR TITLE
Add some useful additional printer columns for TidbMonitor 

### PR DESCRIPTION
**Pull request by mikechengwei**
### What problem does this PR solve? 
#2169 

### What is changed and how does it work?
1.  add `ready`, `updatedReplicas` and `availableReplicas` columns  to tidbmonitor status and sync .
2. kubectl support printing `READY`  ,`UP-TO-DATE`  and AVAILABLE columns 

We use  deployment to deploy tidbmonitor , so we can print same column as the deployment.
### Check List 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has Go code change

Side effects

 - None

### CODE REVIEW

**Comment by mikechengwei** [comment]
@cofyc Hi, we want to  use sts deploy tidbmonitor in  #2968 . So  using deploymentStatus directly is in vain. What do you think?

**Comment by cofyc** [comment]
> @cofyc Hi, we want to use sts deploy tidbmonitor in #2968 . So using deploymentStatus directly is in vain. What do you think?

I think it's good to use sts, then we don't need to create PVCs manually in our controller. The most important thing is the migration. We need to provide a smooth migration experience, otherwise, users may lose data. 

Do you have a detailed design for this change?

**Comment by cofyc** [comment]
btw, I left a few comments on your original PR https://github.com/pingcap/tidb-operator/pull/2967 PTAL

**Comment by mikechengwei** [comment]
@cofyc  I have see you comments  . I have a question whether we should use READY ,UP-TO-DATE and AVAILABLE  fields directly to avoid migration caused by sts deploy.

I am currently referring to the code in kubernetes below:
https://github.com/kubernetes/kubernetes/blob/23b66eaabd3a535dbee6474638c5bf51e78fbcfa/pkg/printers/internalversion/printers.go#L1940-L1956

**Comment by cofyc** [comment]
I'm fine not adding any printer columns until we migrated to the StatefulSet.

**Comment by mikechengwei** [comment]
ok

**Comment by DanielZhangQD** [comment]
@mikechengwei When do you plan to work on the issue that deploys monitor with sts, if you're going to work on it in a short time, I think you can wait until then to add the printer columns, WDYT?

**Comment by mikechengwei** [comment]
No problem. I will finish sts design in next week and do it at weekend in this week.

**Pull request closed without merging**
