### PR TITLE
Separate TidbMonitor's prometheus scrape job

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve? 
Closes https://github.com/pingcap/tidb-operator/issues/1610

### What is changed and how does it work?
Separate the TidbMonitor's Prometheus scrape job to show the correct metrics.

### CODE REVIEW

**Comment by cofyc** [comment]
this is related to Prometheus, @qiffang can you do the final review?

**Comment by cofyc** [comment]
failed to cherry-pick into 1.1, @Yisaer cherry-pick manually?

**Comment by Yisaer** [comment]
> failed to cherry-pick into 1.1, @Yisaer cherry-pick manually?

sure, worikng on it. @cofyc

**Pull request merged**
