### PR TITLE
Remove the apiserver and related packages (#3298)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3298 to release-1.1

---

Signed-off-by: Lonng <heng@lonng.org>

### What problem does this PR solve? 

The apiserver has been deprecated and doesn't plan to release recently, to make the codebase clean, we should remove it and related packages. We can revert this PR if we want to continue develop this feature in the future.

### What is changed and how does it work?

Remove the apiserver and related packages.

### Check List 

Tests 

 - Unit test
 - E2E test

Code changes

 - Has Go code change

### Does this PR introduce a user-facing change?:

```release-note
Remove the apiserver and related packages
```

### CODE REVIEW

**Review by july2993 — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
@Yisaer I think the file charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml should not be touched for the apiserver change, WDYT? cc @lonng

**Comment by lonng** [comment]
@DanielZhangQD Seems it's a mistake. The master has this change also, I think it's better to change master first and cherry-pick again. How do you think?

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD Seems it's a mistake. The master has this change also, I think it's better to change master first and cherry-pick again. How do you think?

OK.

**Comment by DanielZhangQD** [comment]
I think we can delete `hack/aa-codegen.sh` and `hack/update-test-codegen.sh`, the current change removed part of the options which will fail to execute the scripts.
`hack/update-all.sh` needs to be updated if `hack/update-test-codegen.sh` removed.
cc @lonng

**Pull request merged**
