### PR TITLE
Remove resign ddl owner logic for tidb-servers

### LINKED ISSUE #1225: Remove resign DDL owner logic to keep things simple
## Feature Request

AFAIK, TiDB server will clean up the etcd session upon shutdown(either gracefully or not), which release the lock of DDL owner path and trigger a leader election immediately. Therefore, we can remove the resign DDL owner logic and leave it to TiDB server.

Example:

* Send SIGTERM (shutdown but not gracefully) to tidb-2, which is the current DDL owner:
```
➜  ~ kubectl exec -it wuyelei-tidb-2 -c tidb -- sh
/ # kill -s TERM 1
/ # command terminated with exit code 137
```

* Log of tidb-1 and tidb-2 shows that tidb-2 clean up the session and tidb-1 get the owner immediately:

```
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.000 +00:00] [INFO] [signal_posix.go:54] ["got signal to exit"] [signal=terminated]
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.000 +00:00] [INFO] [server.go:572] ["[server] graceful shutdown."]
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.001 +00:00] [WARN] [manager.go:281] ["is not the owner"] ["owner info"="[ddl] /tidb/ddl/fg/owner ownerManager 1f2b2e8c-2e3a-4913-940c-8c37617e06d7"]
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.001 +00:00] [INFO] [http_status.go:263] ["listen failed"] [error="http: Server closed"]
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.001 +00:00] [INFO] [manager.go:239] ["etcd session is done, creates a new one"] ["owner info"="[ddl] /tidb/ddl/fg/owner ownerManager 1f2b2e8c-2e3a-4913-940c-8c37617e06d7"]
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.001 +00:00] [INFO] [manager.go:243] ["break campaign loop, NewSession failed"] ["owner info"="[ddl] /tidb/ddl/fg/owner ownerManager 1f2b2e8c-2e3a-4913-940c-8c37617e06d7"] [error="context canceled"] [errorVerbose="context canceled\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.4/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.4/juju_adaptor.go:15\ngithub.com/pingcap/tidb/owner.contextDone\n\tgithub.com/pingcap/tidb@/owner/manager.go:371\ngithub.com/pingcap/tidb/owner.NewSession\n\tgithub.com/pingcap/tidb@/owner/manager.go:142\ngithub.com/pingcap/tidb/owner.(*ownerManager).campaignLoop\n\tgithub.com/pingcap/tidb@/owner/manager.go:241\nruntime.goexit\n\truntime/asm_amd64.s:1357"]
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.003 +00:00] [INFO] [manager.go:292] ["revoke session"] ["owner info"="[ddl] /tidb/ddl/fg/owner ownerManager 1f2b2e8c-2e3a-4913-940c-8c37617e06d7"] []
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.003 +00:00] [INFO] [ddl_worker.go:113] ["[ddl] DDL worker closed"] [worker="worker 1, tp general"] ["take time"=16.577µs]
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.003 +00:00] [INFO] [ddl_worker.go:113] ["[ddl] DDL worker closed"] [worker="worker 2, tp add index"] ["take time"=4.853µs]
wuyelei-tidb-2 tidb [2019/11/23 14:28:29.003 +00:00] [INFO] [session_pool.go:85] ["[ddl] closing sessionPool"]
wuyelei-tidb-1 tidb [2019/11/23 14:28:29.008 +00:00] [INFO] [manager.go:316] ["get owner"] ["owner info"="[ddl] /tidb/ddl/fg/owner ownerManager 16bb2bf4-6c29-4229-ba91-4208ca04a4fa"] [ownerID=16bb2bf4-6c29-4229-ba91-4208ca04a4fa]
```

cc @tennix @weekface @zimulala

### PR DESCRIPTION
**Pull request by aylei**
Signed-off-by: Aylei <rayingecho@gmail.com>

close #1225 
### Check List 

Tests 
 - E2E test

Code changes

 - Has Go code change

### Does this PR introduce a user-facing change?:
 
 ```release-note
Operator will not resign ddl owner when upgrading tidb-servers anymore because tidb-server will transfer ddl owner automatically on shutdown.
 ```

### CODE REVIEW

**Comment by cofyc** [comment]
[webhook in e2e](https://github.com/pingcap/tidb-operator/blob/f67ed33213d82643f2f6aada38fa093ec0f66fcd/tests/pkg/webhook/pods.go#L75-L98) should be updated too because it validates that pod to delete should not be DDL owner

**Comment by aylei** [comment]
> [webhook in e2e](https://github.com/pingcap/tidb-operator/blob/f67ed33213d82643f2f6aada38fa093ec0f66fcd/tests/pkg/webhook/pods.go#L75-L98) should be updated too because it validates that pod to delete should not be DDL owner

Thanks, working on it

**Comment by aylei** [comment]
@weekface @cofyc @tennix PTAL

**Pull request merged**
