### PR TITLE
Implement the feature of pod serial number control for TiCDC using asts

### PR DESCRIPTION
**Pull request by charleszheng44**
### What problem does this PR solve?
Implement the feature of pod serial number control for TiCDC using asts

### What is changed and how does it work?
Users can scale in desired cdc replicas by setting the annotation `ticdc.tidb.pingcap.com/delete-slots` in TiDB Cluster CR.
```yaml
metadata:
  annotations:
    ticdc.tidb.pingcap.com/delete-slots: '[1]'
```

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [x] Unit test 
- [x] E2E test 
- [x] Manual test 

Create Kind Cluster locally
```
kind create cluster
```
Build operator locally
```
make operator-docker
```
Load operator image to kind cluster
```
kind load docker-image localhost:5000/pingcap/tidb-operator:latest
```
Create related CRDs
```
kubectl create -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml
kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/v1.4.2/manifests/advanced-statefulset-crd.v1.yaml
```
Deploy operator with advanced sts enabled
```
kubectl create ns tidb-admin
helm install --namespace tidb-admin tidb-operator pingcap/tidb-operator --set operatorImage=localhost:5000/pingcap/tidb-operator --set features={AdvancedStatefulSet=true} --set advancedStatefulset.create=true
```
Get tidb-cluster sample yaml and create the tidb-cluster
```
curl -LO https://raw.githubusercontent.com/pingcap/tidb-operator/master/examples/basic/tidb-cluster.yaml
# edit the yaml and add ticdc config
#  ticdc:
#     baseImage: pingcap/ticdc
#     replicas: 3
kubectl apply -f tidb-cluster.yaml
```
Wait for tidb cluster to be ready, there will be three ticdc instances running
```
kubectl get po -A
#...
default              basic-ticdc-0                                     1/1     Running   0          20m
default              basic-ticdc-1                                     1/1     Running   0          20m
default              basic-ticdc-2                                     1/1     Running   0          20m
#...
```
Scale in ticdc cluster and delete the basic-ticdc-1 by adding annotation and change ticdc config
add following annotation to the tidb-cluster cr
```yaml
ticdc.tidb.pingcap.com/delete-slots: '[1]'
```
update the ticdc config 
```yaml
ticdc:
    baseImage: pingcap/ticdc
    replicas: 2
```
Wait a while, the basic-ticdc-1 will be deleted
```
kubectl get po -A
#...
default              basic-ticdc-0                                     1/1     Running   0          20m
default              basic-ticdc-2                                     1/1     Running   0          20m
#...

```
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Allow scaling in specified TiCDC pod by adding annotation `ticdc.tidb.pingcap.com/delete-slots` to TiDB Cluster CR.
```

### CODE REVIEW

**Comment by cchenkey** [comment]
https://github.com/charleszheng44/tidb-operator/blob/feat/del-slots-cdc/pkg/manager/member/tidb_member_manager.go#L1010-L1023

Does StatefulSetUpdateStrategy also need support？

**Comment by charleszheng44** [comment]
> https://github.com/charleszheng44/tidb-operator/blob/feat/del-slots-cdc/pkg/manager/member/tidb_member_manager.go#L1010-L1023
> 
> Does StatefulSetUpdateStrategy also need support in ticdc_member_manager.go？

Just add support to `ticdc_member_manager.go`

**Review by overvenus — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Review by cchenkey — APPROVED** [review]

**Review by KanShiori — APPROVED** [review]

**Pull request merged**
