### PR TITLE
Update google-kubernetes-tutorial.md

### PR DESCRIPTION
**Pull request by thecodeassassin**
Fixed typo in docs

### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Helm charts change
 - Has Go code change
 - Has CI related scripts change
 - Has documents change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:
 
 ```release-note

 ```

### CODE REVIEW

**Comment by gregwebs** [comment]
Thanks @thecodeassassin
BTW, you might try our [terraform based setup](https://github.com/pingcap/tidb-operator/tree/master/deploy/gcp) where we have been focusing our efforts lately.

**Comment by thecodeassassin** [comment]
@gregwebs thanks for the tip. Does it also show how to span tidb over multiple (geographic) clusters?

**Comment by gregwebs** [comment]
Our operator is designed to run on a single K8s cluster. So you would need to have a federated K8s cluster . You can look at using tidb-ansible for deploying across datacenters.

**Pull request merged**
