### PR TITLE
[DNM] Create named port for tikv status 20180 (#2410)

### PR DESCRIPTION
**Pull request by tirsen**
#2410

### CODE REVIEW

**Comment by tirsen** [comment]
I have tested this locally and I can confirm that Prometheus can now scrape metrics after adding that port. Prometheus could not scrape the metrics even if using an integer `targetPort` because Prometheus auto discovery can't discover ports without names.

**Comment by Yisaer** [comment]
This changes is ok for me but I think it would upgrade tikv if user starts upgrade operator from v1.0.x. I think #2466 could also solve the problem so I tend to receive this request but not port to the v1.1

**Comment by cofyc** [comment]
hi, @yeya24 does your suggested solution in #2466 solves this problem too?

@tirsen we try to avoid change TiKV default statefulset spec as possible as we can because it will trigger a rolling update.

**Comment by tirsen** [comment]
It would be cool to have changes that are applied after the diffing so that you can make "optional" changes that are only applied after other changes that does require a restart (such as an image upgrade).

**Comment by DanielZhangQD** [comment]
@tirsen We will fix this in another PR to add a parameter to control this to avoid rolling update TiKV by default, thanks!

**Pull request closed without merging**
