### PR TITLE
e2e: add dmctl and TLS cases for DM, some fix for previous cases

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve?

- add an E2E test case for dmctl
- add an E2E test case for TLS
- update DM image to fix the problem in DM (fixed in https://github.com/pingcap/dm/pull/1672)
- change the checkpoint table name to avoid checkpoint reuse

part of #2868 

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [x] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
None
```

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@DanielZhangQD @july2993 I also fix some issues for previous cases, PTAL

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by july2993 — APPROVED** [review]

**Pull request merged**
