### PR TITLE
fix apiVersion for DaemonSet

### PR DESCRIPTION
**Pull request by nyurik**
# What problem does this PR solve? 

`apiVersion: extensions/v1beta1` has marked DaemonSet as obsolete, switching to `apps/v1`

### What is changed and how does it work?

`apiVersion: extensions/v1beta1` has marked DaemonSet as obsolete

### Check List 

?

### Does this PR introduce a user-facing change?:
 
 ```release-note
NONE
 ```

### CODE REVIEW

**Comment by tennix** [comment]
@nyurik Thank you for your contribution! Could you change other obsolete `apiVersion`s too?

**Comment by nyurik** [comment]
> @nyurik Thank you for your contribution! Could you change other obsolete `apiVersion`s too?
@tennix are you refering to other files in the repo?  I only looked at this one (was looking at auto-RAID creation), so I could verify it working. I didn't validate any other ones.

**Comment by tennix** [comment]
The `tidb-scheduler` `Deployment` also uses `extensions/v1beta1` apiVersion, I think this needs to be changed too.

**Comment by nyurik** [comment]
@tennix there are [12 places](https://github.com/pingcap/tidb-operator/search?q="extensions%2Fv1beta1"&unscoped_q="extensions%2Fv1beta1"&type=Code) that use DaemonSet and Deployment with `extensions/v1beta1`, and I am a bit weary of making search/replace changes in a project that I'm not too familiar with :)

**Comment by tennix** [comment]
I think it's OK since the minimal requirement is k8s 1.12.5. The `apps` API group should be always enabled.

**Comment by tennix** [comment]
@nyurik Hi, if you don't want to fix other obsolete apiVersion in this PR, we can merge it for now and fix others in later PRs.

**Pull request merged**
