### PR TITLE
do not run UT in jenkins anymore

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve?

We upload UT coverage from GitHub actions and E2E coverage from Jenkins. but for Codecov, it wouldn't merge reports and show the coverage until all reports uploaded  (from both CI Providers).

After a PR merged into the master branch, GitHub Actions will upload the UT coverage (from #3838), so Jenkins no need to upload UT coverage anymore (and it shouldn't, otherwise Codecov will become confused because of two reports from one provider but no report from another).

### What is changed and how does it work?

remove UT tests and coverage upload in Jenkins pipeline.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
None
```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by handlerww — APPROVED** [review]
LGTM

**Comment by handlerww** [comment]
well done!

**Pull request merged**
