### PR TITLE
Remove DinD related scripts and document

### PR DESCRIPTION
**Pull request by shonge**
### What problem does this PR solve? 
#1156 
### Check List 

Tests 

 - E2E test

Code changes

 - Has CI related scripts change

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:
 
 ```release-note
Remove DinD related scripts
 ```

### CODE REVIEW

**Comment by cofyc** [comment]
Thanks! can you remove DinD-related docs too?

**Comment by tennix** [comment]
I think the CONTRIBUTING guide also needs to be updated to drop the dind part.

**Comment by cofyc** [comment]
Thanks!

**Pull request merged**
