### PR TITLE
apiserver: delete apiserver scaffold

### PR DESCRIPTION
**Pull request by shuijing198799**
### What problem does this PR solve? 
delete apiserver fold from tidb-operator
### What is changed and how does it work?
same as the first question
### Check List 

Tests 

 - No code

Code changes

 - Has Helm charts change
 - Has Go code change
 - Has CI related scripts change
 - Has documents change

### CODE REVIEW

**Comment by cofyc** [comment]
```
[2019-09-04T08:39:16.647Z] Get https://hub.pingcap.net/v2/: dial tcp 172.16.4.5:443: connect: no route to host

script returned exit code 1
```

/run-e2e-in-kind

**Comment by shuijing198799** [comment]
[2019-09-05T07:43:56.740Z] E0905 07:43:49.174003       1 backup.go:31] cluster:[cluster3] deploy happen error: failed to launch backup job: timed out waiting for the condition

[2019-09-05T07:43:56.740Z] panic: failed to launch backup job: timed out waiting for the condition

[2019-09-05T07:43:56.740Z] 

[2019-09-05T07:43:56.740Z] goroutine 242 [running]:

[2019-09-05T07:43:56.740Z] github.com/pingcap/tidb-operator/tests/slack.NotifyAndPanic(0x1b5e0a0, 0xc0002f8750)

[2019-09-05T07:43:56.740Z] 	/home/jenkins/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/slack/slack.go:155 +0x271

[2019-09-05T07:43:56.740Z] github.com/pingcap/tidb-operator/tests.(*operatorActions).BackupRestoreOrDie(0xc000419aa0, 0xc00000a780, 0xc00000ab40)

[2019-09-05T07:43:56.740Z] 	/home/jenkins/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/backup.go:99 +0x66

[2019-09-05T07:43:56.740Z] main.main.func4(0xc000047c90)

[2019-09-05T07:43:56.740Z] 	/home/jenkins/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/cmd/e2e/main.go:163 +0x18b

[2019-09-05T07:43:56.740Z] created by main.main

[2019-09-05T07:43:56.740Z] 	/home/jenkins/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/cmd/e2e/main.go:170 +0x7c9

[2019-09-05T07:43:57.300Z] ++ kubectl get po tidb-operator-e2e -n tidb-operator-e2e '-ojsonpath={.status.phase}'

PTAL @weekface @cofyc @xiaojingchen

**Pull request merged**
