### PR TITLE
add proposal for deploy tidb cluster across kubernetes clusters

### PR DESCRIPTION
**Pull request by DanielZhangQD**
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
remove https://github.com/pingcap/tidb-operator/blob/master/docs/design-proposals/2020-06-12-heterogeneous-design-for-tidb-cluister.md?

**Comment by DanielZhangQD** [comment]
> remove https://github.com/pingcap/tidb-operator/blob/master/docs/design-proposals/2020-06-12-heterogeneous-design-for-tidb-cluister.md?

No, I will update it later. That's a different proposal.

**Pull request merged**
