### PR TITLE
Fix codecs error for non-ASCII char in tidbInitializer job passwordSecret

### PR DESCRIPTION
**Pull request by handlerww**
### What problem does this PR solve? 
https://github.com/pingcap/tidb-operator/issues/3568 
The non-ASCII characters in the password will lead the init script broken down.

### What is changed and how does it work?
Add encoding params in tidbInitializer scripts.
### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Create the root secret
```bash
kubectl create secret generic tidb-secret --from-literal=root=おはよう
```

Modify the examples/initialize/tidb-initializer.yaml and apply, the job is finished
```output
basic-tidb-initializer-gz7tw               0/1     Completed   0          68s
```

Check if the password works

```bash
[root@handlerww-multi-cluster init]# mysql -h 127.0.0.1 -u root -P 4000 
ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: NO)
[root@handlerww-multi-cluster init]# mysql -h 127.0.0.1 -u root -P 4000 -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 945
Server version: 5.7.25-TiDB-v4.0.8 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

Code changes

- Has Go code change

Side effects

- Breaking backward compatibility

Related changes

- Need to cherry-pick to the release branch
- Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
Fix codecs error for non-ASCII char password in tidbInitializer job
```

### CODE REVIEW

**Comment by tennix** [comment]
Have you manually tested this?

**Review by lonng — APPROVED** [review]
LGTM

**Comment by handlerww** [comment]
> Have you manually tested this?

Done. The description of the PR is updated.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Pull request merged**
