### PR TITLE
fix: when tls client is enabled for tidb, br will crash the controller manager

### LINKED ISSUE #3524: tidb-controller-manager panics during backup with BR
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Backup with BR with TiDB Operator v1.1.7 + TiDB Cluster v4.0.8.
TLS enabled for the components and between the TiDB server and clients.
```
---
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: br16
  namespace: ns0
spec:
  br:
    cluster: ns0
    clusterNamespace: ns0
  s3:
    provider: aws
    region: ap-northeast-1
    secretName: s3-secret
    bucket: backup
    prefix: br16
```
**What did you expect to see?**
Backup succeeds.
**What did you see instead?**
tidb-controller-manager panic with the following logs:
```
I1126 06:16:44.915990       1 tidb_initializer_controller.go:66] Starting tidbinitializer controller
I1126 06:16:44.916081       1 tidb_cluster_controller.go:95] Starting tidbcluster controller
E1126 06:16:44.922002       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 551 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1a997a0, 0x2f9c1d0)
        k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1a997a0, 0x2f9c1d0)
        runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb-operator/pkg/backup/backup.(*backupManager).makeBackupJob(0xc000763800, 0xc000efa000, 0x1d25a93, 0x8, 0x20ecb80, 0xc000cf0640, 0xb)
        github.com/pingcap/tidb-operator@/pkg/backup/backup/backup_manager.go:358 +0xc49
github.com/pingcap/tidb-operator/pkg/backup/backup.(*backupManager).syncBackupJob(0xc000763800, 0xc000efa000, 0x0, 0x0)
        github.com/pingcap/tidb-operator@/pkg/backup/backup/backup_manager.go:143 +0x870
github.com/pingcap/tidb-operator/pkg/backup/backup.(*backupManager).Sync(0xc000763800, 0xc000efa000, 0x0, 0x0)
        github.com/pingcap/tidb-operator@/pkg/backup/backup/backup_manager.go:60 +0x85
github.com/pingcap/tidb-operator/pkg/controller/backup.(*defaultBackupControl).updateBackup(...)
        github.com/pingcap/tidb-operator@/pkg/controller/backup/backup_control.go:68
github.com/pingcap/tidb-operator/pkg/controller/backup.(*defaultBackupControl).UpdateBackup(0xc00037ff00, 0xc000efa000, 0x0, 0x0)
        github.com/pingcap/tidb-operator@/pkg/controller/backup/backup_control.go:64 +0x161
github.com/pingcap/tidb-operator/pkg/controller/backup.(*Controller).syncBackup(...)
        github.com/pingcap/tidb-operator@/pkg/controller/backup/backup_controller.go:134
github.com/pingcap/tidb-operator/pkg/controller/backup.(*Controller).sync(0xc0007638c0, 0xc000be2c98, 0x8, 0x0, 0x0)
        github.com/pingcap/tidb-operator@/pkg/controller/backup/backup_controller.go:130 +0x1f0
github.com/pingcap/tidb-operator/pkg/controller/backup.(*Controller).processNextWorkItem(0xc0007638c0, 0x0)
        github.com/pingcap/tidb-operator@/pkg/controller/backup/backup_controller.go:94 +0x106
github.com/pingcap/tidb-operator/pkg/controller/backup.(*Controller).worker(0xc0007638c0)
        github.com/pingcap/tidb-operator@/pkg/controller/backup/backup_controller.go:82 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0008f40b0)
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008f40b0, 0x3b9aca00, 0x0, 0x1, 0xc0008e28a0)
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0008f40b0, 0x3b9aca00, 0xc0008e28a0)
        k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88 +0x4d
created by github.com/pingcap/tidb-operator/pkg/controller/backup.(*Controller).Run
        github.com/pingcap/tidb-operator@/pkg/controller/backup/backup_controller.go:74 +0x1d9
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x16d6cb9]
```

### PR DESCRIPTION
**Pull request by dragonly**
### What problem does this PR solve? 

When `TidbCluster.spec.tidb.tlsClient.enabled` is set to `true`, and apply a `Backup` as follows, `tidb-controller-manager` will panic and crash.

fixes #3524

### What is changed and how does it work?

The root cause is that br.spec.from is nil, we should check and access its members

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)
    - apply `backup-s3.yaml` and check that backup files are at the correct s3 bucket, `tidb-controller-manager` is fine
    ```yaml
    # backup-s3.yaml
    apiVersion: pingcap.com/v1alpha1
    kind: Backup
    metadata:
        name: br16
        namespace: ns0
    spec:
        br:
            cluster: ns0
            clusterNamespace: ns0
        s3:
            provider: aws
            region: ap-northeast-1
            secretName: s3-secret
            bucket: backup
            prefix: br16
    ```

Code changes

- Has Go code change

Side effects

None

Related changes

- Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
Fix the issue that syncing `Backup` CR will crash tidb-controller-manager when TLS client is enabled for TiDB
```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by DanielZhangQD** [comment]
@dragonly Please add release notes.
Please also go through the release notes guide https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md.

**Review by shuijing198799 — APPROVED** [review]
LGTM

**Review by july2993 — APPROVED** [review]

**Pull request merged**
