### PR TITLE
set all components minimum replicas to 0

### PR DESCRIPTION
**Pull request by handlerww**
### What problem does this PR solve?

All components should support 0 replicas for graceful shutdown, especially in multicluster TiDB.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
set all components minimum replicas to 0
```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by KanShiori — APPROVED** [review]

**Comment by KanShiori** [comment]
@handlerww  maybe need to fix e2e case

**Comment by handlerww** [comment]
> 

This check is based on the store information in PD, not the CRD. There's no need to update this case.

**Pull request merged**
