### PR TITLE
improve e2e semantics (#3673)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3673 to release-1.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb-operator repo:
git pr https://github.com/pingcap/tidb-operator/pull/3701
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb-operator.git pr/3701:release-1.1-18666d4f601d
```

---

### What problem does this PR solve?

improve semantics of e2e test case.

### What is changed and how does it work?

- describe test cases purpose and steps more clearly
- fail fast if critical conditions are not met

### Code changes

- [x] Has Go code change
- [x] Has CI related scripts change

### Tests

- [ ] Unit test 
- [x] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
NONE
```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by dragonly** [comment]
don't merge for now, need more tests for stability

**Pull request closed without merging**
