### PR TITLE
add more error information for controller

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
supplement of https://github.com/pingcap/tidb-operator/pull/2851.

### What is changed and how does it work?
Add more error log info.

### Check List 

Tests 

 - Unit test
 - E2E test

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
Please fix the conflict.

**Comment by lichunzhu** [comment]
> Please fix the conflict.

fixed

**Comment by DanielZhangQD** [comment]
Please also fix the ci.

**Comment by lichunzhu** [comment]
> Please also fix the ci.

done

**Pull request merged**
