### PR TITLE
docs: note helm versions in deployment docs

### LINKED ISSUE #552: helm v3.0.0-alpha.1 not work correctly
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Run `terraform apply` as documented.
**What did you expect to see?**

**What did you see instead?**
屏幕快照 2019-06-04 下午2 07 18

### PR DESCRIPTION
**Pull request by AstroProfundis**
### What problem does this PR solve? 
Fix #552 
### What is changed and how it works?
`helm` v3.0.0+ are not supported yet.
### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has documents change

Side effects

 - N/A

Related changes

 - N/A

### Does this PR introduce a user-facing change?:
 
 ```release-note

 ```

### CODE REVIEW

**Comment by weekface** [comment]
Do we need to note all these helm versions? https://github.com/pingcap/tidb-operator/search?l=Markdown&q=helm

**Comment by lucklove** [comment]
> Do we need to note all these helm versions? https://github.com/pingcap/tidb-operator/search?l=Markdown&q=helm

My point is that if it's not tested, then the answer is no. And if it's tested and v3.x not work at all, then the answer is yes. (Of course we should test these cases in the end)

In the case of this pr, the v3.x not work, so we need to document it.

**Comment by tennix** [comment]
Yes, I think all places when mentioning helm versions should be noted.

**Comment by tennix** [comment]
Helm 3.0 is a huge refactor. I don't think we can run with helm v3.0 in any of the environment without modification of the charts, so all the documents need to be updated.

**Pull request merged**
