### PR TITLE
split basic e2e cases into smaller chunks

### PR DESCRIPTION
**Pull request by dragonly**
### What problem does this PR solve?

make each e2e test case smaller.
partially contribute to #3652

### What is changed and how does it work?

make basic test cases smaller

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [x] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
None
```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
Could you please help update the version here https://github.com/pingcap/tidb-operator/blob/master/tests/e2e/util/image/image.go#L30-L33 to the latest v3.0.x and v4.0.x (no need to test v3.1.x)?

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Pull request merged**
