### PR TITLE
upgrade local-volume-provisioner to v2.3.2

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### What is changed and how does it work?
Update local-volume-provisioner image to latest release.

### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Helm charts change
 - Has Go code change
 - Has CI related scripts change
 - Has documents change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:
 
 ```release-note

 ```

### CODE REVIEW

**Comment by yeya24** [comment]
CI failed, do i need to change the e2e test code?
I am not sure that why here we need to patch this local pv. https://github.com/pingcap/tidb-operator/blob/fc3ad44f2c3796166ee5a6c526a4c06e397aa62d/tests/actions.go#L642

**Comment by cofyc** [comment]
it's necessary, CI may fail because of temporary failures.

**Comment by weekface** [comment]
@yeya24 The CI env was broken when i last run it. I will run the e2e test tonight again.

**Pull request merged**
