### PR TITLE
add some useful packages to the bastion

### PR DESCRIPTION
**Pull request by kolbe**
### What problem does this PR solve? 

I noticed that the bastion could be more useful if it had a few additional packages.

### What is changed and how does it work?

This PR adds screen, git, vim, bind-utils to bastion-userdata.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

I deployed with these changes in place and the new packages were available on the bastion host.

Related changes

 - Need to cherry-pick to the release branch

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by gregwebs** [comment]
We should stop using a bastion for the purpose of SSH and instead utilize [AWS SSM](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html). It works really well, reduces cost, and increases security.

Then we need to make sure it is easy to modify security group rules to connect to MySQL from an instance of your choice where you can install whatever you want.

**Comment by tennix** [comment]
> We should stop using a bastion for the purpose of SSH and instead utilize [AWS SSM](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html). It works really well, reduces cost, and increases security.
> 
> Then we need to make sure it is easy to modify security group rules to connect to MySQL from an instance of your choice where you can install whatever you want.

I agree. But this PR looks fine, we should do SSM switching in other PRs. You can create an issue as a reminder for SSM integration.

**Pull request merged**
