### PR TITLE
Record event as grafana annotation in stability test

### PR DESCRIPTION
**Pull request by aylei**
A fix for sst truncate case checking is also included.

@weekface @qiffang @zyguan @xiaojingchen PTAL

Signed-off-by: Aylei <rayingecho@gmail.com>

### CODE REVIEW

**Comment by weekface** [comment]
@aylei please resolve conflicts.

**Comment by aylei** [comment]
@xiaojingchen Thanks for your review and I've resolved some merge conflicts since your last review, could you please take a look again?
&
/run-e2e-tests

**Pull request merged**
