### PR TITLE
Set the default externalTrafficPolicy to be Local for TiDB service

### PR DESCRIPTION
**Pull request by shinnosuke-okada**
### What problem does this PR solve? 
https://github.com/pingcap/tidb-operator/issues/879

### What is changed and how does it work?
The default externalTrafficPolicy is now set to be Local

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
1. Deploy to AWS from /tidb-operator/deploy/aws out-of-box
2. Run `kubectl describe service my-cluster-tidb -n my-cluster` and verify the value of externalTrafficPolicy.

Code changes

 - Has Helm charts change

Side effects

 - Breaking backward compatibility

Related changes

 - N/A

### Does this PR introduce a user-facing change?:
 
 ```release-note
NONE
 ```

### CODE REVIEW

**Comment by weekface** [comment]
Can we do this in the terraform deployment script? This looks like a breaking change to the operator.

**Comment by shinnosuke-okada** [comment]
@weekface: which part/file do you have in mind for "the terraform deployment script"? `/tidb-operator/deploy/modules`?

**Comment by tennix** [comment]
@shinnosuke-okada The default values.yaml for terraform module https://github.com/pingcap/tidb-operator/blob/master/deploy/modules/aws/tidb-cluster/values/default.yaml

**Comment by weekface** [comment]
@aylei PTAL

**Comment by shinnosuke-okada** [comment]
@weekface @tennix: Sure! Let me move the change to `/tidb-operator/deploy/modules`.
Although it's a backward incompatible change, I modified the helm chart default as I couldn't think of a use case where multiple TiDB pods should be scheduled per node.

**Comment by tennix** [comment]
Users may deploy tidb-cluster in their IDC where a node can have multiple pods scheduled.

**Comment by shinnosuke-okada** [comment]
Addressed the review comment. PTAL.

**Pull request merged**
