### PR TITLE
Add 10s sleep prior to warmup exit for sidecars to upload logs

### PR DESCRIPTION
**Pull request by michaelmdeng**
### What problem does this PR solve?

Add sleep before exiting the warmup container. This is needed to give time to sidecar containers to upload logs/metrics before warmup completes.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 

Ran EBS snapshot restore w/ updated warmup pod and observe restore functions as expected.

- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]
LGTM

**Review by BornChanger — APPROVED** [review]

**Comment by BornChanger** [comment]
@michaelmdeng please sign cla with the correct id.

**Pull request merged**
