### PR TITLE
marketplace update

### PR DESCRIPTION
**Pull request by gregwebs**
document the service account
fix some issues with the manual install

### CODE REVIEW

**Comment by gregwebs** [comment]
This was seen when installing with the default service account on a new cluster:

```
Error from server (Forbidden): error when creating "STDIN": roles.rbac.authorization.k8s.io "tidb-controller-manager" is forbidden: attempt to grant extra privileges: [{[*] [] [services] []
 []} {[*] [] [events] [] []} {[create] [] [endpoints] [] []} {[get] [] [endpoints] [] []} {[update] [] [endpoints] [] []} {[get] [] [persistentvolumeclaims] [] []} {[list] [] [persistentvol
umeclaims] [] []} {[watch] [] [persistentvolumeclaims] [] []} {[update] [] [persistentvolumeclaims] [] []} {[delete] [] [persistentvolumeclaims] [] []} {[get] [] [pods] [] []} {[list] [] [p
ods] [] []} {[watch] [] [pods] [] []} {[update] [] [pods] [] []} {[delete] [] [pods] [] []} {[*] [apps] [statefulsets] [] []} {[*] [pingcap.com] [tidbclusters] [] []}] user=&{system:service
account:default:default 2920a667-5b1c-11e9-96a3-42010a8000a8 [system:serviceaccounts system:serviceaccounts:default system:authenticated] map[]} ownerrules=[{[create] [authorization.k8s.io]
 [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi
/* /version /version/]}] ruleResolutionErrors=[]
```

**Comment by tennix** [comment]
Have you tested on GCP marketplace? If so, I think we can merge it now.

**Comment by gregwebs** [comment]
yes, please merge.

**Pull request merged**
