### PR TITLE
use tc.Timezone()

### PR DESCRIPTION
**Pull request by better0332**
### What problem does this PR solve?
tc.Spec.Timezone not have default value, should use tc.Timezone()

### What is changed and how does it work?
use tc.Timezone()

### Code changes

- [*] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]

**Comment by DanielZhangQD** [comment]
@better0332 Please fix the UT.

**Pull request merged**
