### PR TITLE
tidbmonitor support dynamic configuration.

### LINKED ISSUE #4020: Dynamic update tidbmonitor when prometheus configuration update.
## Feature Request

**Is your feature request related to a problem? Please describe:**
Dynamic update tidbmonitor when prometheus or grafana configuration changed.

**Describe the feature you'd like:**
I think we can add a field called `revision` into `spec` and `status`.
When configuration changed, we can generate new revision hash value and set it to `spec` revision field. The tidbmonitor  find the status and spec field value not equal, it can trigger sts recreating.

### PR DESCRIPTION
**Pull request by mikechengwei**
### What problem does this PR solve?
Fix #4020 

### What is changed and how does it work?
Update configmap name replace with hash suffix.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

```release-note
tidbmonitor support dynamic configuration.
```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
@mikechengwei Sorry that we have not got time to review this PR yet, we will do that after v1.2.0-rc.2 released this week.

**Comment by mikechengwei** [comment]
This plan is abandoned.

**Pull request closed without merging**
