### PR TITLE
bump operator version to 1.4.4

### PR DESCRIPTION
**Pull request by WizardXiao**
### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by WangLe1321 — APPROVED** [review]

**Comment by WizardXiao** [comment]
release-1.4.4 should be based on release-1.4

**Pull request closed without merging**
