### PR TITLE
update status for tidb initializer

### LINKED ISSUE #3565: TidbInitializer: status field has not been updated
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**

master

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

```
 kubectl  --kubeconfig louis-aws-shoot-60fd7d38.kubeconfig get po -n tidb1335183645282930688
NAME                                   READY   STATUS      RESTARTS   AGE
db-discovery-57d4db8c-s6vhg            1/1     Running     0          6h40m
db-monitor-0                           3/3     Running     0          6h40m
db-pd-0                                1/1     Running     0          6h40m
db-tidb-0                              2/2     Running     0          6h36m
db-tidb-extra-access-69dd7b5b6-6hpnr   2/2     Running     0          6h40m
db-tidb-initializer-8pjmk              0/1     Completed   0          6h36m
db-tikv-0                              1/1     Running     0          6h37m
db-tikv-1                              1/1     Running     0          6h37m
db-tikv-2                              1/1     Running     0          6h37m
```

**What did you do?**

Create a TidbInitializer CR

**What did you expect to see?**
TidbInitializer CR's status field should be updated.

**What did you see instead?**
```
# kubectl  --kubeconfig louis-aws-shoot-60fd7d38.kubeconfig get job -n tidb1335183645282930688  db-tidb-initializer -o yaml
...
status:
  completionTime: "2020-12-05T11:30:58Z"
  conditions:
  - lastProbeTime: "2020-12-05T11:30:58Z"
    lastTransitionTime: "2020-12-05T11:30:58Z"
    status: "True"
    type: Complete
  startTime: "2020-12-05T11:30:44Z"
  succeeded: 1
```

```
# kubectl  --kubeconfig louis-aws-shoot-60fd7d38.kubeconfig get tidbinitializers.pingcap.com -n tidb1335183645282930688 -o yaml
apiVersion: v1
items:
- apiVersion: pingcap.com/v1alpha1
  kind: TidbInitializer
  metadata:
    creationTimestamp: "2020-12-05T11:30:44Z"
    generation: 1
    name: db-initializer
    namespace: tidb1335183645282930688
    resourceVersion: "1928818"
    selfLink: /apis/pingcap.com/v1alpha1/namespaces/tidb1335183645282930688/tidbinitializers/db-initializer
    uid: 6413a280-774d-4fdd-8056-3052221ebe41
  spec:
    cluster:
      name: db
      namespace: tidb1335183645282930688
    image: tnir/mysqlclient
    initSql: CREATE TABLE IF NOT EXISTS test.test (id INT UNSIGNED AUTO_INCREMENT,
      PRIMARY KEY (id));
    passwordSecret: tidb-secret
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

### PR DESCRIPTION
**Pull request by DanielZhangQD**
### What problem does this PR solve? 
Fix #3565
### What is changed and how does it work?
Update code to sync the Job status to the status of TidbInitializer CR
### Check List 

Tests 

- Unit test
- E2E test
- Manual test (add detailed scripts or steps below)
  Create a TidbCluster and a TidbInitializer, check that after the initializer job is finished, the status of TidbInitializer is synced:
```
apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  creationTimestamp: "2020-11-30T03:22:08Z"
  generation: 1
  name: demo
  namespace: default
  resourceVersion: "11491845"
  selfLink: /apis/pingcap.com/v1alpha1/namespaces/default/tidbinitializers/demo
  uid: 3a7e64dd-32bb-11eb-87fe-06b1f522197d
spec:
  cluster:
    name: t
    namespace: default
  image: tnir/mysqlclient
  initSql: create database app;
  passwordSecret: tidb-secret
status:
  completionTime: "2020-11-30T03:22:22Z"
  conditions:
  - lastProbeTime: "2020-11-30T03:22:22Z"
    lastTransitionTime: "2020-11-30T03:22:22Z"
    status: "True"
    type: Complete
  phase: Completed
  startTime: "2020-11-30T03:22:08Z"
  succeeded: 1
```

```
apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  creationTimestamp: "2020-12-07T07:39:30Z"
  generation: 1
  name: t0
  namespace: ns0
  resourceVersion: "11527583"
  selfLink: /apis/pingcap.com/v1alpha1/namespaces/ns0/tidbinitializers/t0
  uid: 5732f8b4-385f-11eb-87fe-06b1f522197d
spec:
  cluster:
    name: ns0
    namespace: ns0
  image: tnir/mysqlclient
  initSql: create database app;
  passwordSecret: tidb-secret
status:
  conditions:
  - lastProbeTime: "2020-12-07T07:39:41Z"
    lastTransitionTime: "2020-12-07T07:39:41Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 1
  phase: Failed
  startTime: "2020-12-07T07:39:32Z"
```

Code changes

- Has Go code change

Related changes

- Need to cherry-pick to the release branch
- Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
Sync `Status` field for the TidbInitializer CR
```

### CODE REVIEW

**Review by lonng — COMMENTED** [review]
/lgtm

**Review by handlerww — APPROVED** [review]
LGTM

**Review by LinuxGit — APPROVED** [review]
LGTM

**Pull request merged**
