### PR TITLE
Add spec.pd.maxFailoverCount to limit max failover replicas for PD

### LINKED ISSUE #2116: Abe to disable auto-failover for PD in CR
## Feature Request

**Is your feature request related to a problem? Please describe:**

Unable to disable auto-failover in `TidbCluster` CR.

**Describe the feature you'd like:**

We can add `pd.spec.maxFailoverCount` to support this.

https://github.com/pingcap/tidb-operator/blob/f24da05dd147f7aaedea27bf42f779d0190ed4ed/pkg/manager/member/pd_failover.go#L34-L37

https://github.com/pingcap/tidb-operator/blob/f24da05dd147f7aaedea27bf42f779d0190ed4ed/pkg/manager/member/pd_failover.go#L102-L105 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 
fixes #2116 
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Go code change
 - Has CI related scripts change
 - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
Add `spec.pd.maxFailoverCount` field to limit max failover replicas for PD
```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
Can this also fix https://github.com/pingcap/tidb-operator/issues/1895 if cherry-pick to release-1.0?

**Comment by cofyc** [comment]
this PR can't be picked into 1.0 directly, but it's possible to implement it in 1.0.

**Comment by DanielZhangQD** [comment]
> this PR can't be picked into 1.0 directly, but it's possible to implement it in 1.0.

@cofyc Please also implement this in 1.0 to fix #1895, thanks!

**Pull request merged**
