### PR TITLE
fix-rcloneImage

### PR DESCRIPTION
**Pull request by yiduoyunQ**
### What problem does this PR solve?

follow doc [restore-data-using-tidb-lightning](https://docs.pingcap.com/tidb-in-kubernetes/stable/restore-data-using-tidb-lightning), when we [Grant permissions by associating IAM with ServiceAccount](https://docs.pingcap.com/tidb-in-kubernetes/stable/grant-permissions-to-remote-storage#grant-permissions-by-associating-iam-with-serviceaccount) and [deploy TiDB Lightning](https://docs.pingcap.com/tidb-in-kubernetes/stable/restore-data-using-tidb-lightning#step-3-deploy-tidb-lightning), we get error below:
89f51de1-083b-4028-aefa-8e38281bce5b

after some test and investigate, we found the default value of `rcloneImage` in `helm inspect values pingcap/tidb-lightning` is rclone/rclone:1.55.1, and there has an [known issue](https://github.com/rclone/rclone/issues/5762) in rclone and fixed in rclone v1.57.0

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by KanShiori** [comment]
Thanks for the PR.

I think we also need to update the rclone version in `tidb-backup-manager`, could you please upgrade the version in Dockerfile?
```dockerfile
FROM pingcap/alpine-glibc:alpine-3.14.3-gcompat
ARG TARGETARCH
ARG RCLONE_VERSION=v1.51.0
ARG SHUSH_VERSION=v1.4.0
```

**Review by KanShiori — APPROVED** [review]

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
