### PR TITLE
fix tikv failover

### LINKED ISSUE #362: It takes 2 hours for tikv failover
When a tikv is down, its state in pd firstly turns to `Disconnected`, then becomes `Down` after 1 hour. According to failover logic [here](https://github.com/pingcap/tidb-operator/blob/4c183422345d8fe9e5a450f3729339ee01684767/pkg/manager/member/tikv_failover.go#L51), it will take 2 hours for failover. Does this behave as expected? It's little misleading.

### PR DESCRIPTION
**Pull request by weekface**
This pr fixes #362 

TiKV should failover a period of time (default is 5m) after it becomes "Down"(It will become down after 30 minutes after Disconnect).

30 + 5 = 35

### CODE REVIEW

**Comment by tennix** [comment]
Please resolve the conflicts @weekface

**Comment by weekface** [comment]
> LGTM
> BTW, does the TODO matter? or is it related to this PR?
> 
> > TODO we should confirm the tombstone exists, important!!!!!! ...

Where is the TODO?

**Comment by zyguan** [comment]
> > LGTM
> > BTW, does the TODO matter? or is it related to this PR?
> > > TODO we should confirm the tombstone exists, important!!!!!! ...
> 
> Where is the TODO?

In this commit https://github.com/pingcap/tidb-operator/pull/368/commits/e6d7947685e8d84e3bdb6dbd1df86b4543c05af8

**Pull request merged**
