### PR TITLE
warmup-image: test WAL files while warming up

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve?

This PR added an ad-hoc precheck for the warmup script.

### What is changed and how does it work?

We will run `ldb dump_wal` on each log files found. 
It is an ad-hoc solution because the version of `ldb` is hard-coded.
Please don't merge them and only use this to build the `warmup` image.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 

I run this on a simple storage that contains some corrupted SST files:

CleanShot 2024-03-06 at 17 02 14@2x

- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by WangLe1321 — APPROVED** [review]

**Review by nkg- — COMMENTED** [review]
What is the path to merging this PR. The corruption check seems meaningful enough to merge to master.

**Comment by BornChanger** [comment]
The hardcode tikv version seems acceptable now.

**Review by BornChanger — APPROVED** [review]

**Comment by BornChanger** [comment]
/cherry-pick-release-1.5

**Pull request merged**
