### PR TITLE
Normalize the name of all methods receiver of types (#3403)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3403 to release-1.1

---

Signed-off-by: Lonng <heng@lonng.org>

### What problem does this PR solve? 

The receiver names of all methods don't have a consistent naming way, even some receivers name like a magic string.

### What is changed and how does it work?

This PR normalizes the name of all methods receiver of types.

### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test

Code changes

 - Has Go code change

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by DanielZhangQD** [comment]
@lonng Please fix the CI.

**Comment by lonng** [comment]
@DanielZhangQD done

**Review by july2993 — APPROVED** [review]

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Pull request merged**
