### PR TITLE
fix pd READY column and use tmp file in verify script

### PR DESCRIPTION
**Pull request by cofyc**
### Check List 

Tests 

 - Unit test
 - E2E test
 - Stability test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has Helm charts change
 - Has Go code change
 - Has CI related scripts change
 - Has documents change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:
 
 ```release-note

 ```

### CODE REVIEW

**Comment by Yisaer** [comment]
As `crd.yaml` is generated by `to-crdgen`. The additionalPrinterColums should be fixed at `pkg/util/crdutil.go`
```go
tidbClusterPDReadyColumn = extensionsobj.CustomResourceColumnDefinition{
		Name:        "Ready",
		Type:        "integer",
		Description: "The desired replicas number of PD cluster",
		JSONPath:    ".spec.pd.readyReplicas",
}
```
And regenerate it at your local. @cofyc

**Comment by cofyc** [comment]
@Yisaer @onlymellb can you approve again? I've rebased on the master.

**Pull request merged**
