### PR TITLE
*: also fix for other two codegen scripts

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Follow #4727

### What is changed and how does it work?

`goimports` and `openapi` also need to apply patch for go117 and above.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Comment by xhebox** [comment]
ping @csuzhangxc @KanShiori

**Review by KanShiori — APPROVED** [review]

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
