### PR TITLE
Bump helm to v2.17.0

### LINKED ISSUE #3610: "helm delete tidb-operator --purge" doesn't delete tidb-controller-manager Deployment
## Bug Report

**What version of Kubernetes are you using?**

v1.18.2

**What version of helm are you using?**
v2.9.1

**What version of TiDB Operator are you using?**

v1.1.7

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

```
NAME                      PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-storage (default)   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  19h
standard                  rancher.io/local-path          Delete          WaitForFirstConsumer   false                  19h
```

**What's the status of the TiDB cluster pods?**

**What did you do?**

```
[root@localhost tidb-operator]# helm install --name tidb-operator --namespace tidb-admin pingcap/tidb-operator
NAME:   tidb-operator
LAST DEPLOYED: Thu Dec 17 00:46:04 2020
NAMESPACE: tidb-admin
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME                     DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
tidb-controller-manager  1        1        1           0          1s
tidb-scheduler           1        1        1           0          1s

==> v1/Pod(related)
NAME                                      READY  STATUS             RESTARTS  AGE
tidb-controller-manager-7bbc47cfb5-fzxs9  0/1    ContainerCreating  0         1s
tidb-scheduler-9df5c9fcd-65lwr            0/2    ContainerCreating  0         1s

==> v1/ConfigMap
NAME                   DATA  AGE
tidb-scheduler-policy  1     1s

==> v1/ServiceAccount
NAME                     SECRETS  AGE
tidb-controller-manager  1        1s
tidb-scheduler           1        1s

==> v1beta1/ClusterRole
NAME                                   AGE
tidb-operator:tidb-controller-manager  1s
tidb-operator:tidb-scheduler           1s

==> v1beta1/ClusterRoleBinding
NAME                                   AGE
tidb-operator:tidb-controller-manager  1s
tidb-operator:kube-scheduler           1s
tidb-operator:tidb-scheduler           1s
tidb-operator:volume-scheduler         1s


NOTES:
Make sure tidb-operator components are running:

    kubectl get pods --namespace tidb-admin -l app.kubernetes.io/instance=tidb-operator

[root@localhost tidb-operator]# helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
tidb-operator   1               Thu Dec 17 00:46:04 2020        DEPLOYED        tidb-operator-v1.1.7    v1.1.7          tidb-admin
[root@localhost tidb-operator]# kubectl -n tidb-admin get deploy
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
tidb-controller-manager   1/1     1            1           17s
tidb-scheduler            1/1     1            1           17s
[root@localhost tidb-operator]# helm delete tidb-operator --purge
release "tidb-operator" deleted
```

**What did you expect to see?**
`tidb-controller-manager` and `tidb-scheduler` be deleted

**What did you see instead?**
```
[root@localhost tidb-operator]# helm ls --all
[root@localhost tidb-operator]# kubectl -n tidb-admin get deploy
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
tidb-controller-manager   1/1     1            1           2m34s
tidb-scheduler            1/1     1            1           2m34s
```
Tiller's log:
```
[tiller] 2020/12/16 16:47:32 uninstall: Deleting tidb-operator
[tiller] 2020/12/16 16:47:32 executing 0 pre-delete hooks for tidb-operator
[tiller] 2020/12/16 16:47:32 hooks complete for pre-delete tidb-operator
[storage] 2020/12/16 16:47:32 updating release "tidb-operator.v1"
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-scheduler" Deployment
[kube] 2020/12/16 16:47:32 Using reaper for deleting "tidb-scheduler"
[kube] 2020/12/16 16:47:32 the server could not find the requested resource
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-controller-manager" Deployment
[kube] 2020/12/16 16:47:32 Using reaper for deleting "tidb-controller-manager"
[kube] 2020/12/16 16:47:32 the server could not find the requested resource
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-operator:tidb-controller-manager" ClusterRoleBinding
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-operator:kube-scheduler" ClusterRoleBinding
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-operator:tidb-scheduler" ClusterRoleBinding
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-operator:volume-scheduler" ClusterRoleBinding
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-operator:tidb-controller-manager" ClusterRole
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-operator:tidb-scheduler" ClusterRole
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-controller-manager" ServiceAccount
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:32 Starting delete for "tidb-scheduler" ServiceAccount
[kube] 2020/12/16 16:47:32 warning: failed to load schema: SchemaError(io.k8s.api.networking.v1.IPBlock): invalid object doesn't have additional properties
[kube] 2020/12/16 16:47:33 Starting delete for "tidb-scheduler-policy" ConfigMap
[tiller] 2020/12/16 16:47:33 executing 0 post-delete hooks for tidb-operator
[tiller] 2020/12/16 16:47:33 hooks complete for post-delete tidb-operator
[tiller] 2020/12/16 16:47:33 purge requested for tidb-operator
[storage] 2020/12/16 16:47:33 deleting release "tidb-operator.v1"
[storage] 2020/12/16 16:48:02 listing all releases with filter
[storage] 2020/12/16 16:48:23 listing all releases with filter
```
And I found this issue:
https://github.com/helm/helm/issues/3889
Fixed in helm v2.11:
https://github.com/helm/helm/pull/4420

### PR DESCRIPTION
**Pull request by shonge**
### What problem does this PR solve?

bump helm to v2.17.0
Fix #3610 

### Code changes

- [ ] Has Go code change
- [x] Has CI related scripts change

### Tests

- [x] Unit test 
- [x] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [x] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
NONE
```

### CODE REVIEW

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by dragonly** [comment]
Since this only affects CI tests, IMO it's better to leave the release notes as `NONE`.

**Comment by dragonly** [comment]
LGTM, nice work 👍

**Review by dragonly — APPROVED** [review]

**Pull request merged**
