### PR TITLE
fix e2e job on master branch

### PR DESCRIPTION
**Pull request by cofyc**
### What problem does this PR solve? 

we should fetch heads refs too.

### Check List 

Tests 

 - Unit test
 - E2E test

### CODE REVIEW

**Comment by onlymellb** [comment]
@cofyc I tested this solution and found that it still doesn't work, I fixed this problem in this pr #1207, I have tested it and can work

**Comment by cofyc** [comment]
closing this in favor of https://github.com/pingcap/tidb-operator/pull/1207.

**Pull request closed without merging**
