### PR TITLE
fix gke volume zone problem

### LINKED ISSUE #241: WaitForFirstConsumer PD stuck in pending
in gke-storage.yaml I add

```
volumeBindingMode: WaitForFirstConsumer
```

I create a new kubernetes cluster, and deploy tidb.

```
$ kubectl get pod -n tidb1

NAME                              READY   STATUS      RESTARTS   AGE
demo-monitor-5988ddc86c-mf2nz     2/2     Running     0          8m
demo-monitor-configurator-xgrd2   0/1     Completed   0          8m
demo-pd-0                         0/1     Pending     0          8m
demo-tidb-initializer-qfbgq       1/1     Running     0          8m
```

```
$ kubectl get pvc -n tidb1
NAME           STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pd-demo-pd-0   Pending                                      pd-ssd         8m
```

There are no pv. The pod shows a warning:

```
$ kubectl describe -n tidb1 pod demo-pd-0
...
Events:
  Type     Reason            Age                   From            Message
  ----     ------            ----                  ----            -------
  Warning  FailedScheduling  2m26s (x37 over 12m)  tidb-scheduler  0/3 nodes are available: 3 node(s) didn't find available persistent volumes to bind.
```

### PR DESCRIPTION
**Pull request by weekface**
This pr fixes #241 #247 

Use the default predicates and priority functions:

> Creating scheduler with fit predicates 'map[NoVolumeZoneConflict:{} MaxEBSVolumeCount:{} MaxAzureDiskVolumeCount:{} NoDiskConflict:{} GeneralPredicates:{} PodToleratesNodeTaints:{} CheckVolumeBinding:{} MaxGCEPDVolumeCount:{} MatchInterPodAffinity:{} CheckNodeMemoryPressure:{} CheckNodeDiskPressure:{} CheckNodePIDPressure:{} CheckNodeCondition:{}]' and priority functions 'map[SelectorSpreadPriority:{} InterPodAffinityPriority:{} LeastRequestedPriority:{} BalancedResourceAllocation:{} NodePreferAvoidPodsPriority:{} NodeAffinityPriority:{} TaintTolerationPriority:{}]'

@tennix @gregwebs PTAL

### CODE REVIEW

**Comment by gregwebs** [comment]
The pod doesn't get scheduled when I try this PR. I am using the latest stable release tag for tidb-operator in my values.yaml, maybe that is the problem?

```
$ kubectl logs -n tidb-admin tidb-scheduler-66c98d4464-fnh95 -c kube-scheduler | tail -2
I1222 23:52:23.415046       1 factory.go:950] Registering predicate: CheckNodePIDPressure
F1222 23:52:23.415059       1 plugins.go:235] Invalid configuration: Predicate type not found for CheckNodePIDPressure
```

It looks like CheckNodePIDPressure was added in this PR.

**Comment by weekface** [comment]
which kube version are you using? version less then v1.11 doesn't have `CheckNodePIDPressure `:https://github.com/pingcap/tidb-operator/pull/248/commits/549940e53041b2e9003a6a4174ab03cb3ec7b39a

**Comment by gregwebs** [comment]
1.11.5

**Comment by weekface** [comment]
https://github.com/pingcap/tidb-operator/blob/a523c0955e0c9df789656ac801e2e687132ae8be/charts/tidb-operator/values.yaml

Modify this `kubeSchedulerImage` to v1.11 to match your kubernetes version. I will add comments about this soon.

**Comment by gregwebs** [comment]
Is it possible for us to leave the `kubeSchedulerImage` empty and automatically pick a correct image for the K8s version being used?

**Comment by weekface** [comment]
We can get kubernetes version by `.Capabilities.KubeVersion.GitVersion`, but it may not work as expected.

For example, on GKE, it may return `v1.11.5-gke.5`, but there is no this image:

```
$ docker pull k8s.gcr.io/hyperkube:v1.11.5-gke.5
Error response from daemon: manifest for k8s.gcr.io/hyperkube:v1.11.5-gke.5 not found
$ docker pull gcr.io/google-containers/hyperkube:v1.11.5-gke.5
Error response from daemon: manifest for gcr.io/google-containers/hyperkube:v1.11.5-gke.5 not found
```
It works without the `-gke.5` suffix:

```
$ docker pull gcr.io/google-containers/hyperkube:v1.11.5
v1.11.5: Pulling from google-containers/hyperkube
7ba0c30ce37c: Already exists
b279612e5ae0: Already exists
e71da3cc4e18: Already exists
67e7cb2bca0b: Already exists
a888c881dad1: Already exists
87d7bd35b027: Already exists
0a9ceea11156: Pull complete
1846139271dc: Pull complete
Digest: sha256:9ab2a70d2e2a9de6e2f1f29a12effbf6d1d358f2e2c0022c4ce9dadc383a6901
Status: Downloaded newer image for gcr.io/google-containers/hyperkube:v1.11.5
```

**Comment by gregwebs** [comment]
It works now.

**Comment by weekface** [comment]
> We could strip any dashed ending? Or use `.Major` and `.Minor` instead? If it doesn't work then the user must specify an image, which is the same as now, but it seems like we might be able to automate it for most users.

This is a little hack.

**Comment by gregwebs** [comment]
> This is a little hack.

What's wrong with using `.Major` and `.Minor`? If we aren't going to adopt such an approach, lets just leave the image empty and make the user fill it out rather than pre-filling with an incorrect image.

**Pull request merged**
