### PR TITLE
Fix: Optimization PodsAreChanged function

### LINKED ISSUE #3895: Optimization for `PodsAreChanged` function
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

In the function here https://github.com/pingcap/tidb-operator/blob/master/tests/e2e/util/pod/pod.go#L40-L45, it's not reasonable to return an error if the Pod has been changed, which is already indicated by the `true`.
And the return value check for this function in the caller functions should also be updated accordingly.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by shonge**
### What problem does this PR solve?

Close #3895 

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [x] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Optimization PodsAreChanged function
```

### CODE REVIEW

**Comment by shonge** [comment]
@DanielZhangQD PTAL

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Pull request merged**
