### PR TITLE
README: update links and add info

### PR DESCRIPTION
**Pull request by CaitinChen**
### What problem does this PR solve?

update links and add info

### What is changed and how does it work?

- Optimized some links in the README file
- Added some related content

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [x] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
`NONE`
```

### CODE REVIEW

**Comment by CaitinChen** [comment]
@lilin90 PTAL

**Review by handlerww — APPROVED** [review]
LGTM

**Review by lonng — APPROVED** [review]
LGTM

**Pull request merged**
