### PR TITLE
fix backup and restore time column

### PR DESCRIPTION
**Pull request by zjj2wry**
### What problem does this PR solve? 
Fix https://github.com/pingcap/tidb-operator/issues/2659
### What is changed and how does it work?
previous: 
```
➜  ~ kubectl get bk -o wide
NAME              BACKUPPATH   BACKUPSIZE   COMMITTS   STARTED   COMPLETED   AGE
demo1-backup-s3                0                       14m       14m         14m
```
now:
```
➜  ~ kubectl get bk -o wide
NAME              BACKUPPATH   BACKUPSIZE   COMMITTS   STARTED                COMPLETED              AGE
demo1-backup-s3                0                       2020-06-16T10:20:28Z   2020-06-16T10:20:28Z   9m51s
```

### Check List 

Tests 

- [ ]  - Unit test
- [ ]  - E2E test
- [ ]  - Stability test
- [x]  - Manual test (add detailed scripts or steps below)
- [ ]  - No code

Code changes

- [x]  - Has Go code change
- [ ]  - Has CI related scripts change
- [ ]  - Has Terraform scripts change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Does this PR introduce a user-facing change?:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
https://github.com/pingcap/tidb-operator/issues/2659

The data-time is already displayed. Is it necessary to add  the duration field?

**Comment by DanielZhangQD** [comment]
> #2659
> 
> The data-time is already displayed. Is it necessary to add the duration field?

I think it's OK with the current implementation.

**Pull request merged**
