### PR TITLE
Skip corruption check on last WAL

### PR DESCRIPTION
**Pull request by michaelmdeng**
### What problem does this PR solve?

During EBS snapshot warmup, only check WALs up to the last one for corruption. We expect some corruptions in the last WAL due to race between fsync and EBS snapshot, and we can recover from these scenarios.

Also updates WAL log file pattern since logs can contain variable length log nos.

### Code changes

- [ ] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [x] Manual test 

Executed warmup w/ these changes and observe warmup progress normally w/out checking the last WAL

- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note

```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]
LGTM, thanks!

**Review by YuJuncen — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]

**Review by WangLe1321 — APPROVED** [review]

**Review by csuzhangxc — APPROVED** [review]

**Pull request merged**
