### PR TITLE
[WIP]DNM: test CI for contributor

### PR DESCRIPTION
**Pull request by rrbot1995**

### CODE REVIEW

**Comment by rrbot1995** [comment]
Thanks for your approve ! The CI seems failed for random reason, I want to rerun it .
Since I have no permission to type `/run-e2e-test`, Could you:
1. type `/add-to-whilelist` so I can run command.
2. help type `/ok-to-test`  or `/run-e2e-test` again

**Comment by qrr1995** [comment]
Fine, I would help you to run it .  
God bless this is a stable PR so I would not run it again and again :)

**Pull request closed without merging**
