### PR TITLE
Fix default tidb-drainer config

### PR DESCRIPTION
**Pull request by shinnosuke-okada**
### What problem does this PR solve? 
https://github.com/pingcap/tidb-operator/issues/792

### What is changed and how does it work?
Default tidb-drainer config is adjusted to be compatible with the latest drainer config format.
To be more specific:
detect-interval is moved out from [syncer]
db-type value is changed from pb to file
compression is moved out from [syncer] and renamed to compressor

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
1. Deploy tidb-drainer chart out-of-box to AWS
2. Drainer is successfully deployed and running

Code changes

 - Has Helm charts change

Side effects

 - Breaking backward compatibility

Related changes

 - N/A

### Does this PR introduce a user-facing change?:
 
 ```release-note
NONE
 ```

### CODE REVIEW

**Comment by aylei** [comment]
@tennix @weekface PTAL

**Comment by aylei** [comment]
@WangXiangUSTC Could you please take a look?

**Comment by july2993** [comment]
start from 2.1.16, pump/drainer will return error when loading some undefined configs.

- detect-interval should be  moved out from [syncer] for all drainer version, i think it's wrongly set here before and will take no any effect for drainer version before 2.1.16
- compressor means Use the specified compressor to compress payload between pump and drainer, I will suggest set it as empty as default. 
- `Syncer.compression` is a wrongly used config by the older version, it's removed since v2.1.9 
and change 'pb' to 'file'(but pb is still accepted by drainer for compatibility)


I will suggest compressor as "" default, rest LGTM

**Comment by shinnosuke-okada** [comment]
@july2993 Addressed your review comment.

To all reviewers: PTAL again. Thanks.

**Pull request merged**
