### PR TITLE
Allow users to customize Prometheus scraping settings

### PR DESCRIPTION
**Pull request by coderplay**
### What problem does this PR solve?

We collect Prometheus metrics in a different way than the way TiDB operator set them up; for example, our metrics collector scrape differs from the port defined by the TiDB operator. However, The TiDB operator will override our custom Prometheus annotations. This PR enables users to customize their Prometheus scraping settings.

### Code changes

- [x] Has Go code change
- [ ] Has CI related scripts change

### Tests

- [ ] Unit test 
- [ ] E2E test 
- [ ] Manual test 
- [ ] No code 

### Side effects

- [ ] Breaking backward compatibility 
- [ ] Other side effects: 

### Related changes

- [ ] Need to cherry-pick to the release branch 
- [ ] Need to update the documentation 

### Release Notes

Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release note.

```release-note
Allow users to customize Prometheus scraping settings 
```

### CODE REVIEW

**Comment by mikechengwei** [comment]
The operator already supports custom prometheus scrap config, ref example : https://github.com/pingcap/tidb-operator/tree/master/examples/monitor-with-externalConfigMap/prometheus.

**Comment by csuzhangxc** [comment]
@coderplay As you change the Prometheus scrape port, how will you change the binding port of the pod?

**Comment by coderplay** [comment]
> @coderplay As you change the Prometheus scrape port, how will you change the binding port of the pod?

Due to some security concerns, we put a proxy on every TiDB pod. The proxy exposes a port for scraping.

**Comment by coderplay** [comment]
@csuzhangxc Could you please take a look at the pull-e2e-kind test?  It showed below message

```
1 tests have failed
There are 0 new tests failing, 1 existing failing and 0 skipped.
```

And could you please let me know if you have any other concerns?

**Review by csuzhangxc — APPROVED** [review]

**Comment by csuzhangxc** [comment]
> pull-e2e-kind test

pull-e2e-kind test is just not stable

**Review by KanShiori — APPROVED** [review]

**Pull request merged**
